"""
Background Scanner API with Server-Sent Events (SSE)
Provides real-time push notifications for trade alerts
"""
from fastapi import APIRouter, HTTPException, Request, Query
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
import asyncio
import json
import logging

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/live-scanner", tags=["Live Scanner"])

# Service instance
_scanner = None


def init_live_scanner_router(scanner):
    """Initialize with scanner service"""
    global _scanner
    _scanner = scanner


# ===================== Models =====================

class WatchlistRequest(BaseModel):
    symbols: List[str] = Field(..., description="Symbols to watch")


class ConfigRequest(BaseModel):
    scan_interval: Optional[int] = Field(default=None, ge=30, le=300)
    enabled_setups: Optional[List[str]] = None


# ===================== SSE Endpoint =====================

@router.get("/stream")
async def stream_alerts(request: Request):
    """
    Server-Sent Events endpoint for real-time alert streaming.
    
    Connect to this endpoint to receive live alerts as they're generated.
    The scanner runs in the background and pushes alerts through this stream.
    
    Usage (JavaScript):
    ```
    const eventSource = new EventSource('/api/live-scanner/stream');
    eventSource.onmessage = (event) => {
        const alert = JSON.parse(event.data);
        console.log('New alert:', alert);
    };
    ```
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    async def event_generator():
        queue = _scanner.subscribe()
        try:
            # Send initial connection message
            yield f"data: {json.dumps({'type': 'connected', 'timestamp': datetime.now(timezone.utc).isoformat()})}\n\n"
            
            # Send current alerts
            for alert in _scanner.get_live_alerts()[:5]:
                yield f"data: {json.dumps({'type': 'alert', 'alert': alert.to_dict()})}\n\n"
            
            # Stream new alerts
            while True:
                # Check if client disconnected
                if await request.is_disconnected():
                    break
                
                try:
                    # Wait for new alert with timeout
                    alert_data = await asyncio.wait_for(queue.get(), timeout=30)
                    yield f"data: {json.dumps({'type': 'alert', 'alert': alert_data})}\n\n"
                except asyncio.TimeoutError:
                    # Send keepalive
                    yield f"data: {json.dumps({'type': 'heartbeat', 'timestamp': datetime.now(timezone.utc).isoformat()})}\n\n"
                    
        except asyncio.CancelledError:
            pass
        finally:
            _scanner.unsubscribe(queue)
    
    return StreamingResponse(
        event_generator(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )


# ===================== Scanner Control =====================

@router.post("/start")
async def start_scanner():
    """Start the background scanner"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    await _scanner.start()
    
    return {
        "success": True,
        "message": "Background scanner started",
        "status": _scanner.get_stats()
    }


@router.post("/stop")
async def stop_scanner():
    """Stop the background scanner"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    await _scanner.stop()
    
    return {
        "success": True,
        "message": "Background scanner stopped"
    }


@router.get("/status")
def get_scanner_status():
    """Get current scanner status and statistics"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        **_scanner.get_stats()
    }


# ===================== Alert Management =====================

@router.get("/alerts")
def get_live_alerts(
    priority: Optional[str] = None,
    ai_agrees_only: bool = False,
    min_ai_confidence: Optional[float] = None,
    sort_by_ai: bool = False
):
    """
    Get current live alerts from the background scanner.
    
    These are real-time alerts generated by continuous scanning.
    
    Parameters:
    - priority: Filter by priority (critical, high, medium, low)
    - ai_agrees_only: Only return alerts where AI agrees with direction
    - min_ai_confidence: Minimum AI confidence (0-100)
    - sort_by_ai: Sort alerts by AI confidence (highest first)
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    from services.enhanced_scanner import AlertPriority
    
    priority_filter = None
    if priority:
        try:
            priority_filter = AlertPriority(priority.lower())
        except ValueError:
            raise HTTPException(status_code=400, detail=f"Invalid priority: {priority}")
    
    alerts = _scanner.get_live_alerts(priority_filter)
    
    # Apply AI filters
    if ai_agrees_only:
        alerts = [a for a in alerts if a.ai_agrees_with_direction]
    
    if min_ai_confidence is not None:
        alerts = [a for a in alerts if a.ai_confidence >= min_ai_confidence]
    
    # Sort by AI confidence if requested
    if sort_by_ai:
        alerts = sorted(alerts, key=lambda a: a.ai_confidence, reverse=True)
    
    return {
        "success": True,
        "count": len(alerts),
        "alerts": [a.to_dict() for a in alerts],
        "scanner_running": _scanner._running,
        "filters_applied": {
            "priority": priority,
            "ai_agrees_only": ai_agrees_only,
            "min_ai_confidence": min_ai_confidence,
            "sort_by_ai": sort_by_ai
        }
    }


@router.get("/alerts/{alert_id}")
def get_alert(alert_id: str):
    """Get a specific alert by ID"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    alert = _scanner.get_alert_by_id(alert_id)
    if not alert:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    return {
        "success": True,
        "alert": alert.to_dict()
    }


@router.post("/alerts/{alert_id}/dismiss")
def dismiss_alert(alert_id: str):
    """Dismiss/acknowledge an alert"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    success = _scanner.dismiss_alert(alert_id)
    
    if not success:
        raise HTTPException(status_code=404, detail="Alert not found")
    
    return {"success": True, "message": "Alert dismissed"}


# ===================== Configuration =====================

@router.post("/watchlist")
def set_watchlist(request: WatchlistRequest):
    """Set the symbols to scan"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    _scanner.set_watchlist(request.symbols)
    
    return {
        "success": True,
        "watchlist": [s.upper() for s in request.symbols],
        "message": f"Watchlist set to {len(request.symbols)} symbols"
    }


@router.get("/watchlist")
def get_watchlist():
    """Get current watchlist"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        "watchlist": _scanner._watchlist,
        "count": len(_scanner._watchlist)
    }


@router.post("/config")
def update_config(request: ConfigRequest):
    """Update scanner configuration"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    if request.scan_interval:
        _scanner.set_scan_interval(request.scan_interval)
    
    if request.enabled_setups is not None:
        _scanner._enabled_setups = set(request.enabled_setups)
    
    return {
        "success": True,
        "config": {
            "scan_interval": _scanner._scan_interval,
            "enabled_setups": list(_scanner._enabled_setups)
        }
    }


@router.get("/config")
def get_config():
    """Get current scanner configuration"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        "scan_interval": _scanner._scan_interval,
        "enabled_setups": list(_scanner._enabled_setups),
        "min_scan_interval": _scanner._min_scan_interval,
        "symbols_per_batch": _scanner._symbols_per_batch,
        "min_rvol_filter": _scanner._min_rvol_filter,
        "auto_execute_enabled": _scanner._auto_execute_enabled
    }


# ===================== Strategy Stats (Win-Rate Tracking) =====================

@router.get("/stats/strategies")
def get_strategy_stats(setup_type: Optional[str] = None):
    """Get win-rate statistics for strategies"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    stats = _scanner.get_strategy_stats(setup_type)
    
    return {
        "success": True,
        "stats": stats
    }


@router.post("/stats/record-outcome")
def record_alert_outcome(
    alert_id: str = Query(..., description="Alert ID"),
    outcome: str = Query(..., description="Outcome: won, lost, expired, cancelled"),
    pnl: float = Query(default=0.0, description="Realized P&L")
):
    """Record the outcome of an alert for win-rate tracking"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    if outcome not in ["won", "lost", "expired", "cancelled"]:
        raise HTTPException(status_code=400, detail="Invalid outcome. Use: won, lost, expired, cancelled")
    
    _scanner.record_alert_outcome(alert_id, outcome, pnl)
    
    return {
        "success": True,
        "message": f"Recorded {outcome} for alert {alert_id}"
    }


# ===================== Auto-Execution Control =====================

@router.post("/auto-execute/enable")
def enable_auto_execute(
    enabled: bool = Query(default=True),
    min_win_rate: float = Query(default=0.55, ge=0.0, le=1.0),
    min_priority: str = Query(default="high", regex="^(critical|high)$")
):
    """Enable or disable auto-execution of high-priority alerts"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    _scanner.enable_auto_execute(enabled, min_win_rate, min_priority)
    
    return {
        "success": True,
        "auto_execute_enabled": enabled,
        "min_win_rate": min_win_rate,
        "min_priority": min_priority
    }


@router.get("/auto-execute/status")
def get_auto_execute_status():
    """Get auto-execution status"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        "enabled": _scanner._auto_execute_enabled,
        "min_win_rate": _scanner._auto_execute_min_win_rate,
        "min_priority": _scanner._auto_execute_min_priority.value,
        "trading_bot_connected": _scanner._trading_bot is not None
    }


# ===================== RVOL Pre-filter =====================

@router.post("/config/rvol-filter")
def set_rvol_filter(
    min_rvol: float = Query(default=0.8, ge=0.0, le=5.0, description="Minimum RVOL to scan symbol")
):
    """Set minimum RVOL filter for pre-filtering symbols"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    _scanner._min_rvol_filter = min_rvol
    
    return {
        "success": True,
        "min_rvol_filter": min_rvol,
        "message": f"Symbols with RVOL < {min_rvol} will be skipped"
    }


# ===================== ADV Volume Filter =====================

@router.get("/config/volume-filter")
def get_volume_filter():
    """Get current average daily volume (ADV) filter configuration"""
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        **_scanner.get_volume_filter_config()
    }


@router.post("/config/volume-filter")
def set_volume_filter(
    min_adv_general: int = Query(default=100_000, ge=0, description="Min ADV for general/swing setups"),
    min_adv_intraday: int = Query(default=500_000, ge=0, description="Min ADV for intraday/scalp setups")
):
    """
    Configure average daily volume (ADV) filters.
    
    - General/Swing setups: Stocks must have ADV >= min_adv_general
    - Intraday/Scalp setups: Stocks must have ADV >= min_adv_intraday
    
    This ensures you only get alerts for liquid stocks that can be traded efficiently.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    _scanner.set_volume_filters(min_adv_general, min_adv_intraday)
    
    return {
        "success": True,
        "min_adv_general": min_adv_general,
        "min_adv_intraday": min_adv_intraday,
        "message": f"Volume filters set: General>={min_adv_general:,}, Intraday>={min_adv_intraday:,}"
    }



# ===================== Symbol Blacklist Management =====================

class BlacklistRequest(BaseModel):
    symbols: List[str] = Field(..., description="Symbols to add/remove from blacklist")


@router.get("/config/blacklist")
def get_blacklist():
    """
    Get the current list of blacklisted symbols.
    
    Blacklisted symbols will NEVER generate scanner alerts, even if they
    pass all other filters. Use this to block known illiquid or problematic tickers.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    return {
        "success": True,
        "blacklisted_symbols": _scanner.get_blacklist(),
        "count": len(_scanner.get_blacklist())
    }


@router.post("/config/blacklist/add")
def add_to_blacklist(request: BlacklistRequest):
    """
    Add symbols to the scanner blacklist.
    
    Blacklisted symbols will be permanently blocked from generating alerts
    until removed from the blacklist.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    result = _scanner.add_to_blacklist(request.symbols)
    
    return {
        "success": True,
        "added": result["added"],
        "total_blacklisted": result["total_blacklisted"],
        "message": f"Added {result['added']} symbols to blacklist"
    }


@router.post("/config/blacklist/remove")
def remove_from_blacklist(request: BlacklistRequest):
    """
    Remove symbols from the scanner blacklist.
    
    Removed symbols will be allowed to generate alerts again if they
    pass volume and quality filters.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    result = _scanner.remove_from_blacklist(request.symbols)
    
    return {
        "success": True,
        "removed": result["removed"],
        "total_blacklisted": result["total_blacklisted"],
        "message": f"Removed {result['removed']} symbols from blacklist"
    }


@router.get("/config/blacklist/check/{symbol}")
def check_blacklist(symbol: str):
    """
    Check if a specific symbol is blacklisted.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")
    
    is_blacklisted = _scanner.is_blacklisted(symbol)
    
    return {
        "success": True,
        "symbol": symbol.upper(),
        "is_blacklisted": is_blacklisted
    }


# 2026-05-01 v19.21 — Premarket Gap-Scanner endpoint backing the new
# operator UI widget. Surfaces "what gapped recently" by joining live
# scanner alerts (gap_*, premarket_high_break, gap_pick_roll) with the
# pushed IB quote stream (for current price + gap_pct snapshot). Returns
# a sorted scrollable list — biggest gappers first.
@router.get("/premarket-gappers")
def get_premarket_gappers(
    window_minutes: int = 8,
    min_gap_pct: float = 2.0,
    max_results: int = 25,
):
    """
    List symbols that gapped within the last `window_minutes` — sorted by
    absolute gap %. Each row carries the current price, prev close, gap %,
    rvol, the alert setup type that fired, and how long ago the alert hit.
    """
    if not _scanner:
        raise HTTPException(status_code=500, detail="Scanner not initialized")

    from datetime import datetime, timezone, timedelta

    # Window cutoff (UTC).
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=max(1, window_minutes))

    # Pull live alerts and filter to gap-related setups in the window.
    GAP_SETUPS = {
        "gap_fade", "gap_give_go", "gap_pick_roll",
        "premarket_high_break", "gap_fill_open",
        # Bare alerts that carry gap_pct on the snapshot are still
        # surfaced via the gap_pct threshold below — these are the
        # explicit setup-type matches for the "freshly gapped" feed.
    }

    alerts = _scanner.get_live_alerts() or []
    rows: List[Dict[str, Any]] = []
    seen_symbols = set()
    for a in alerts:
        try:
            # Skip non-gap alerts unless they carry a meaningful gap_pct.
            atype = getattr(a, "setup_type", "") or ""
            atime_raw = getattr(a, "alert_time", None)
            if atime_raw is None:
                continue
            # alert_time is normally an ISO string; tolerate datetime too.
            if isinstance(atime_raw, str):
                try:
                    atime = datetime.fromisoformat(atime_raw.replace("Z", "+00:00"))
                except ValueError:
                    continue
            else:
                atime = atime_raw
            if atime.tzinfo is None:
                atime = atime.replace(tzinfo=timezone.utc)
            if atime < cutoff:
                continue

            sym = (getattr(a, "symbol", "") or "").upper()
            if not sym or sym in seen_symbols:
                continue

            # Pull gap_pct from the alert metadata if available.
            meta = getattr(a, "metadata", None) or {}
            gap_pct = meta.get("gap_pct") if isinstance(meta, dict) else None
            try:
                gap_pct = float(gap_pct) if gap_pct is not None else None
            except (TypeError, ValueError):
                gap_pct = None

            # Hard filter: only gap setups, OR any setup with |gap_pct| >= min.
            if atype in GAP_SETUPS:
                pass  # always include
            elif gap_pct is not None and abs(gap_pct) >= min_gap_pct:
                pass
            else:
                continue

            seen_symbols.add(sym)
            current_price = getattr(a, "current_price", None) or getattr(a, "trigger_price", None)
            row = {
                "symbol": sym,
                "setup_type": atype,
                "direction": getattr(a, "direction", None),
                "current_price": current_price,
                "trigger_price": getattr(a, "trigger_price", None),
                "gap_pct": gap_pct,
                "rvol": meta.get("rvol") if isinstance(meta, dict) else None,
                "prev_close": meta.get("prev_close") if isinstance(meta, dict) else None,
                "alert_time": atime.isoformat(),
                "alert_age_seconds": int((datetime.now(timezone.utc) - atime).total_seconds()),
                "priority": getattr(getattr(a, "priority", None), "value", None) or str(getattr(a, "priority", "")),
                "market_setup": getattr(a, "market_setup", None),
                "is_countertrend": bool(getattr(a, "is_countertrend", False)),
            }
            rows.append(row)
        except Exception:
            # Defensive — never fail the whole feed for one bad alert.
            continue

    # Sort by absolute gap % descending; alerts without gap_pct go last.
    rows.sort(
        key=lambda r: (r["gap_pct"] is None, -abs(r["gap_pct"] or 0)),
    )
    rows = rows[:max_results]

    return {
        "success": True,
        "window_minutes": window_minutes,
        "min_gap_pct": min_gap_pct,
        "count": len(rows),
        "gappers": rows,
        "scanner_running": getattr(_scanner, "_running", False),
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
