"""
LandscapeGradingService — close the AI-briefing feedback loop.
================================================================

Every morning briefing predicts something concrete: *"I'm seeing 47
names in Gap & Go (top: AAPL, ORCL, MSFT) — today I'm favoring momentum
trades; I'll be looking to avoid mean-reversion on overextended names."*

Without this service those predictions evaporate at end-of-day. With
this service:

  1. Every snapshot generated by `SetupLandscapeService.get_snapshot()`
     gets persisted to the `landscape_predictions` collection.
  2. At EOD, `grade_predictions_for_day(trading_day)` walks
     `alert_outcomes` for the day, groups realized R-multiples by
     Setup family, and grades each prediction A/B/C/D/F based on
     whether the predicted "favored" family carried and the predicted
     "avoided" family stayed away.
  3. The next morning's briefing can cite *yesterday's* receipt:
     *"Yesterday I predicted Gap & Go would carry — it did, +1.20R
     across 14 alerts. Doubling down on momentum today."*

Key collections:
  - `landscape_predictions` — one doc per (trading_day, context).
    Idempotent upsert so re-running the briefing within the same day
    updates the prediction rather than duplicating.
  - `alert_outcomes` (existing) — closed-alert records with
    `setup_type` + `r_multiple` + `closed_at`. Grader reads this.

Grading rubric (kept simple — 5 bands):
  - **A**: predicted family avg R ≥ +0.5 AND avoided family avg R ≤ 0
  - **B**: predicted family avg R ≥ +0.2 AND no big anti-signal
  - **C**: predicted family avg R between -0.2 and +0.2 (mixed)
  - **D**: predicted family avg R ≤ -0.2 (the call was wrong)
  - **F**: predicted family lost AND avoided family won big (worst case)

If we couldn't pin enough alerts to either family, grade = "INSUFFICIENT_DATA".
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# ──────────────────────────── Trade → Setup family mapping ────────────────────────────

def _build_trade_to_setup_family() -> Dict[str, str]:
    """Build a Trade → home-Setup map by inspecting `TRADE_SETUP_MATRIX`.

    Each Trade's "home" Setup is its dominant WITH_TREND cell (the first
    one alphabetically when there are multiple). Used to bucket realized
    alert outcomes into the right Setup family at grading time.
    """
    from services.market_setup_classifier import (
        TRADE_SETUP_MATRIX, TRADE_ALIASES, TradeContext,
    )
    mapping: Dict[str, str] = {}
    for trade, cells in TRADE_SETUP_MATRIX.items():
        with_trend = sorted(
            (s.value for s, ctx in cells.items() if ctx == TradeContext.WITH_TREND)
        )
        if with_trend:
            mapping[trade] = with_trend[0]
        else:
            # All-countertrend trade (e.g., off_sides) — pick the first
            # countertrend cell so we can still score it. Counter-fades
            # are graded as the *opposite* of with-trend wins (they
            # should pay when the daily setup is "wrong").
            counter = sorted(
                (s.value for s, ctx in cells.items() if ctx == TradeContext.COUNTERTREND)
            )
            if counter:
                mapping[trade] = counter[0]
    # Aliases collapse to the canonical's family
    for alias, canonical in TRADE_ALIASES.items():
        if canonical in mapping:
            mapping[alias] = mapping[canonical]
    return mapping


# ──────────────────────────── Data classes ────────────────────────────

@dataclass
class GradedPrediction:
    """Result of grading a single landscape prediction."""
    prediction_id: str
    trading_day: str
    context: str
    top_setup: str
    grade: str                                    # A / B / C / D / F / INSUFFICIENT_DATA
    grade_score: float                            # 0-1 (A=0.9, B=0.7, C=0.5, D=0.3, F=0.1)
    realized_top_setup_avg_r: Optional[float]
    realized_top_setup_n: int
    realized_avoided_avg_r: Optional[float]       # may be None when no avoided-family alerts
    realized_avoided_n: int
    realized_avg_r_all: Optional[float]           # every alert that closed today
    realized_total_alerts: int
    verdict: str                                  # 1-line human summary
    reasoning: List[str] = field(default_factory=list)


# ──────────────────────────── Service ────────────────────────────

class LandscapeGradingService:
    """Records, persists, and grades the briefings' Setup-landscape predictions."""

    # Setup families that "match" each `_SETUP_TRADE_FAMILY` favoring phrase.
    # Used to determine which realized-R bucket the prediction was *avoiding*
    # so we can grade whether the avoidance call was correct.
    _AVOIDED_OPPOSITE = {
        "gap_and_go":             {"overextension", "gap_up_into_resistance"},
        "range_break":            {"overextension"},
        "day_2":                  {"gap_down_into_support", "gap_up_into_resistance",
                                   "overextension", "volatility_in_range"},
        "gap_down_into_support":  {"day_2", "gap_and_go"},  # avoids upside trends
        "gap_up_into_resistance": {"day_2", "gap_and_go"},
        "overextension":          {"day_2", "range_break", "gap_and_go"},
        "volatility_in_range":    {"range_break", "gap_and_go"},
    }

    def __init__(self, db=None):
        self.db = db
        self._trade_family_map: Optional[Dict[str, str]] = None
        if db is not None:
            try:
                db["landscape_predictions"].create_index(
                    [("trading_day", 1), ("context", 1)], unique=True
                )
                db["landscape_predictions"].create_index([("graded_at", 1)])
            except Exception as e:
                logger.debug(f"landscape_predictions index create skipped: {e}")

    @property
    def trade_family_map(self) -> Dict[str, str]:
        if self._trade_family_map is None:
            self._trade_family_map = _build_trade_to_setup_family()
        return self._trade_family_map

    # ───────── Public API ─────────

    async def record_prediction(self, snapshot, context: str) -> Optional[str]:
        """Persist a snapshot's prediction. Idempotent on (trading_day, context).

        Returns the `prediction_id` on success, ``None`` if DB is None or
        the snapshot has nothing actionable to record (all-NEUTRAL).
        """
        if self.db is None:
            return None
        non_neutral = [g for g in snapshot.groups
                       if g.setup != "neutral" and g.count > 0]
        if not non_neutral:
            # Nothing to predict — don't dirty the collection
            return None

        from services.market_setup_classifier import MarketSetup  # noqa: F401
        top = non_neutral[0]
        secondary = non_neutral[1] if len(non_neutral) > 1 else None
        favored, avoided = self._family_phrases(top.setup)
        trading_day = self._trading_day_for(snapshot.timestamp)
        prediction_id = f"lp_{trading_day}_{context}"

        doc = {
            "prediction_id": prediction_id,
            "context": context,
            "trading_day": trading_day,
            "predicted_at": snapshot.timestamp,
            "multi_index_regime": getattr(snapshot, "multi_index_regime", "unknown"),
            "regime_confidence": getattr(snapshot, "regime_confidence", 0.0),
            "top_setup": top.setup,
            "top_setup_count": top.count,
            "top_setup_examples": [s for s, _ in top.examples[:5]],
            "secondary_setup": secondary.setup if secondary else None,
            "secondary_setup_count": secondary.count if secondary else 0,
            "favored_trade_family": favored,
            "avoided_trade_family": avoided,
            "sample_size": snapshot.sample_size,
            "headline": snapshot.headline,
            "narrative": snapshot.narrative,
            "graded_at": None,
            "grade": None,
            "grade_score": None,
            "realized_top_setup_avg_r": None,
            "realized_top_setup_n": None,
            "realized_avoided_avg_r": None,
            "realized_avoided_n": None,
            "realized_avg_r_all": None,
            "realized_total_alerts": None,
            "verdict": None,
            "grade_reasoning": None,
        }
        try:
            self.db["landscape_predictions"].update_one(
                {"trading_day": trading_day, "context": context},
                {"$set": doc, "$setOnInsert": {"created_at": doc["predicted_at"]}},
                upsert=True,
            )
            return prediction_id
        except Exception as e:
            logger.warning(f"record_prediction({trading_day},{context}) failed: {e}")
            return None

    async def grade_predictions_for_day(self, trading_day: Optional[str] = None) -> List[GradedPrediction]:
        """Grade every un-graded prediction for ``trading_day``.

        ``trading_day`` defaults to the current ET date. Returns the list
        of newly-graded predictions; predictions that were already graded
        are not re-touched.
        """
        if self.db is None:
            return []
        if trading_day is None:
            trading_day = self._trading_day_for(
                datetime.now(timezone.utc).isoformat()
            )

        try:
            preds = list(self.db["landscape_predictions"].find(
                {"trading_day": trading_day, "graded_at": None},
                {"_id": 0},
            ))
        except Exception as e:
            logger.warning(f"grade_predictions_for_day load failed: {e}")
            return []
        if not preds:
            return []

        outcomes = self._load_day_outcomes(trading_day)
        all_r = [o["r_multiple"] for o in outcomes if o.get("r_multiple") is not None]
        avg_all = sum(all_r) / len(all_r) if all_r else None

        graded: List[GradedPrediction] = []
        for pred in preds:
            g = self._grade_prediction(pred, outcomes, avg_all)
            try:
                self.db["landscape_predictions"].update_one(
                    {"prediction_id": pred["prediction_id"]},
                    {"$set": {
                        "graded_at": datetime.now(timezone.utc).isoformat(),
                        "grade": g.grade,
                        "grade_score": g.grade_score,
                        "realized_top_setup_avg_r": g.realized_top_setup_avg_r,
                        "realized_top_setup_n": g.realized_top_setup_n,
                        "realized_avoided_avg_r": g.realized_avoided_avg_r,
                        "realized_avoided_n": g.realized_avoided_n,
                        "realized_avg_r_all": g.realized_avg_r_all,
                        "realized_total_alerts": g.realized_total_alerts,
                        "verdict": g.verdict,
                        "grade_reasoning": g.reasoning,
                    }},
                )
            except Exception as e:
                logger.warning(f"grading update for {pred['prediction_id']} failed: {e}")
            graded.append(g)
        logger.info(
            f"[LANDSCAPE GRADING] {trading_day}: graded {len(graded)} predictions "
            f"({sum(1 for g in graded if g.grade in ('A','B'))} good, "
            f"{sum(1 for g in graded if g.grade in ('D','F'))} bad)"
        )
        return graded

    async def get_recent_grades(self, n: int = 5, context: str = "morning") -> List[Dict]:
        """Most-recent N graded predictions for the given context.

        Used by the briefings narrative to surface yesterday's receipts
        ("yesterday I predicted Gap & Go would carry — it did, +1.2R").
        """
        if self.db is None:
            return []
        try:
            cursor = self.db["landscape_predictions"].find(
                {"context": context, "graded_at": {"$ne": None}},
                {"_id": 0},
            ).sort("trading_day", -1).limit(n)
            return list(cursor)
        except Exception as e:
            logger.debug(f"get_recent_grades failed: {e}")
            return []

    async def get_weekly_summary(self, end_date: Optional[str] = None,
                                 context: str = "morning") -> Optional[Dict]:
        """Roll up the past ~7 calendar days of graded predictions into
        a single summary so the Sunday weekend briefing can cite the
        directional accuracy of the past week's calls.

        Returns ``None`` when no graded predictions exist in the window
        — first-week / first-month operation degrades silently.
        """
        if self.db is None:
            return None
        if end_date is None:
            end_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        # 7-day window ending on `end_date` (inclusive)
        try:
            end_dt = datetime.strptime(end_date, "%Y-%m-%d")
        except Exception:
            end_dt = datetime.now(timezone.utc)
        start_dt = end_dt - timedelta(days=7)
        try:
            rows = list(self.db["landscape_predictions"].find(
                {
                    "context": context,
                    "graded_at": {"$ne": None},
                    "trading_day": {
                        "$gte": start_dt.strftime("%Y-%m-%d"),
                        "$lte": end_dt.strftime("%Y-%m-%d"),
                    },
                },
                {"_id": 0, "trading_day": 1, "grade": 1, "grade_score": 1,
                 "verdict": 1, "top_setup": 1,
                 "realized_top_setup_avg_r": 1, "realized_top_setup_n": 1},
            ).sort("trading_day", -1))
        except Exception as e:
            logger.debug(f"get_weekly_summary failed: {e}")
            return None
        if not rows:
            return None
        # Filter out INSUFFICIENT_DATA — those don't tell us anything
        graded = [r for r in rows if r.get("grade") not in (None, "INSUFFICIENT_DATA")]
        if not graded:
            return None
        dist: Dict[str, int] = {}
        scores: List[float] = []
        for r in graded:
            g = r.get("grade", "")
            dist[g] = dist.get(g, 0) + 1
            if r.get("grade_score") is not None:
                scores.append(r["grade_score"])
        avg_score = (sum(scores) / len(scores)) if scores else 0.0
        latest = graded[0]
        # Sum realized R only across the predicted-family realized R
        # (lets us say "this week the bot's morning calls aggregated +X R")
        rs = [r.get("realized_top_setup_avg_r")
              for r in graded if r.get("realized_top_setup_avg_r") is not None]
        avg_top_r = (sum(rs) / len(rs)) if rs else None
        return {
            "n_graded": len(graded),
            "n_total_in_window": len(rows),
            "window_start": start_dt.strftime("%Y-%m-%d"),
            "window_end": end_dt.strftime("%Y-%m-%d"),
            "grade_distribution": dist,
            "avg_score": round(avg_score, 2),
            "avg_top_setup_r": round(avg_top_r, 2) if avg_top_r is not None else None,
            "latest_grade": latest.get("grade"),
            "latest_verdict": latest.get("verdict"),
            "latest_trading_day": latest.get("trading_day"),
        }

    # ───────── Internals ─────────

    def _grade_prediction(self, pred: Dict, outcomes: List[Dict],
                          avg_all: Optional[float]) -> GradedPrediction:
        top_setup = pred.get("top_setup", "")
        avoided_set = self._AVOIDED_OPPOSITE.get(top_setup, set())

        # Bucket each outcome into top-family / avoided-family / other
        top_rs: List[float] = []
        avoided_rs: List[float] = []
        for o in outcomes:
            r = o.get("r_multiple")
            if r is None:
                continue
            family = self.trade_family_map.get(o.get("setup_type", ""))
            if family is None:
                continue
            if family == top_setup:
                top_rs.append(r)
            elif family in avoided_set:
                avoided_rs.append(r)

        top_avg = (sum(top_rs) / len(top_rs)) if top_rs else None
        avoided_avg = (sum(avoided_rs) / len(avoided_rs)) if avoided_rs else None
        total = len(outcomes)

        if top_avg is None or len(top_rs) < 3:
            return GradedPrediction(
                prediction_id=pred["prediction_id"],
                trading_day=pred["trading_day"],
                context=pred["context"],
                top_setup=top_setup,
                grade="INSUFFICIENT_DATA",
                grade_score=0.5,
                realized_top_setup_avg_r=top_avg,
                realized_top_setup_n=len(top_rs),
                realized_avoided_avg_r=avoided_avg,
                realized_avoided_n=len(avoided_rs),
                realized_avg_r_all=avg_all,
                realized_total_alerts=total,
                verdict=(
                    f"Only {len(top_rs)} {top_setup} alerts closed today — "
                    "not enough to grade."
                ),
                reasoning=[
                    f"Predicted family ({top_setup}): n={len(top_rs)}",
                    f"Avoided family ({sorted(avoided_set)}): n={len(avoided_rs)}",
                    f"Total day alerts: {total}",
                ],
            )

        grade, score, reason_lines = self._score_grade(top_avg, avoided_avg)
        verdict = self._verdict_line(top_setup, top_avg, len(top_rs),
                                     avoided_avg, len(avoided_rs), grade)
        return GradedPrediction(
            prediction_id=pred["prediction_id"],
            trading_day=pred["trading_day"],
            context=pred["context"],
            top_setup=top_setup,
            grade=grade,
            grade_score=score,
            realized_top_setup_avg_r=top_avg,
            realized_top_setup_n=len(top_rs),
            realized_avoided_avg_r=avoided_avg,
            realized_avoided_n=len(avoided_rs),
            realized_avg_r_all=avg_all,
            realized_total_alerts=total,
            verdict=verdict,
            reasoning=reason_lines,
        )

    @staticmethod
    def _score_grade(top_avg: float, avoided_avg: Optional[float]
                     ) -> Tuple[str, float, List[str]]:
        """Map (top family avg R, avoided family avg R) → grade + reasoning."""
        # Worst case first: predicted family lost AND avoided family won big
        if top_avg <= -0.2 and (avoided_avg is not None and avoided_avg >= 0.5):
            return "F", 0.10, [
                f"Predicted family lost (avg R={top_avg:+.2f})",
                f"Avoided family won big (avg R={avoided_avg:+.2f}) — "
                "we got it backwards",
            ]
        if top_avg <= -0.2:
            return "D", 0.30, [
                f"Predicted family lost (avg R={top_avg:+.2f}) — "
                "the directional call was wrong",
            ]
        # Strong A — predicted family carried AND avoided family stayed away
        if top_avg >= 0.5 and (avoided_avg is None or avoided_avg <= 0):
            return "A", 0.90, [
                f"Predicted family carried strongly (avg R={top_avg:+.2f})",
                "Avoided family didn't pay" if avoided_avg is None
                else f"Avoided family stayed flat (avg R={avoided_avg:+.2f})",
            ]
        # B — predicted family positive but mixed signal
        if top_avg >= 0.2:
            return "B", 0.70, [
                f"Predicted family was positive (avg R={top_avg:+.2f})",
                f"Avoided family avg R={avoided_avg:+.2f}" if avoided_avg is not None
                else "No avoided-family alerts to compare",
            ]
        # C — mixed
        return "C", 0.50, [
            f"Predicted family was flat-ish (avg R={top_avg:+.2f}) — "
            "no clear edge confirmation",
        ]

    @staticmethod
    def _verdict_line(top_setup: str, top_avg: float, top_n: int,
                      avoided_avg: Optional[float], avoided_n: int,
                      grade: str) -> str:
        from services.setup_landscape_service import SetupLandscapeService
        pretty = SetupLandscapeService._pretty_setup(top_setup)
        head = {
            "A": f"Nailed it — {pretty} carried",
            "B": f"Solid call — {pretty} paid",
            "C": f"Mixed day — {pretty} drifted",
            "D": f"Wrong call — {pretty} faded",
            "F": f"Fully backwards — {pretty} lost while the avoided family won",
        }.get(grade, "Graded")
        return (f"{head}: avg {top_avg:+.2f}R across {top_n} alerts" +
                (f" (avoided family {avoided_avg:+.2f}R/{avoided_n} alerts)"
                 if avoided_avg is not None else ""))

    def _load_day_outcomes(self, trading_day: str) -> List[Dict]:
        """Load `alert_outcomes` rows whose `closed_at` falls within
        the trading day (00:00-23:59 ET, but we just use the date prefix
        on the ISO string for simplicity)."""
        if self.db is None:
            return []
        try:
            # Use a date-prefix scan because closed_at is stored as ISO
            cursor = self.db["alert_outcomes"].find(
                {"closed_at": {"$regex": f"^{trading_day}"}},
                {"_id": 0, "alert_id": 1, "setup_type": 1, "r_multiple": 1,
                 "closed_at": 1, "outcome": 1, "trade_grade": 1},
            )
            return list(cursor)
        except Exception as e:
            logger.debug(f"_load_day_outcomes({trading_day}) failed: {e}")
            return []

    @staticmethod
    def _family_phrases(top_setup: str) -> Tuple[str, str]:
        """Return (favored_phrase, avoided_phrase) for the given Setup
        — same source of truth as `setup_landscape_service`."""
        try:
            from services.setup_landscape_service import _SETUP_TRADE_FAMILY
            entry = _SETUP_TRADE_FAMILY.get(top_setup)
            if entry:
                return entry[1], entry[2]
        except Exception:
            pass
        return "", ""

    @staticmethod
    def _trading_day_for(iso_ts: str) -> str:
        """Convert an ISO UTC timestamp to an ET trading-day string
        (YYYY-MM-DD). Cheap implementation — assumes the briefing fires
        between 00:00 and 23:59 ET, which is true for all four contexts.
        """
        try:
            dt = datetime.fromisoformat(iso_ts.replace("Z", "+00:00"))
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)
            # ET is UTC-5 (EST) or UTC-4 (EDT). Use a safe -5h offset
            # for the date assignment — close enough; off-by-one only
            # affects between 00:00 and 05:00 ET which isn't a briefing
            # window we ship at.
            et_dt = dt - timedelta(hours=5)
            return et_dt.strftime("%Y-%m-%d")
        except Exception:
            return datetime.now(timezone.utc).strftime("%Y-%m-%d")


# ──────────────────────────── Module-level singleton ────────────────────────────

_grading_instance: Optional[LandscapeGradingService] = None


def get_landscape_grading_service(db=None) -> LandscapeGradingService:
    global _grading_instance
    if _grading_instance is None:
        _grading_instance = LandscapeGradingService(db=db)
    elif db is not None and _grading_instance.db is None:
        _grading_instance.db = db
        # late-bind index creation
        try:
            db["landscape_predictions"].create_index(
                [("trading_day", 1), ("context", 1)], unique=True
            )
            db["landscape_predictions"].create_index([("graded_at", 1)])
        except Exception:
            pass
    return _grading_instance
