#!/usr/bin/env python3
"""
apply_naked_sweep_flip_guard_v285.py  (SentCom v19.34.285)

Idempotent applier for the CRM overnight-naked-flip fix.

WHAT IT DOES  (patches backend/services/trading_bot_service.py)
  Hunk A: adds module-level _naked_sweep_flip_decision() (direction-aware).
  Hunk B: in _naked_position_sweep, fetches SIGNED live IB positions once.
  Hunk C: before each naked reissue, refuses to reissue the protective EXIT
          bracket when IB is flat/opposite (would flip the position naked) or
          when position data is unverifiable this cycle. Same-side partials
          still proceed (the v235 magnitude clamp shrinks the order).

WHY
  The v235 clamp (live_position_abs) is direction-BLIND, so an overnight desync
  where IB went flat/opposite let the SELL/BUY exit oversell past zero -> naked
  flip. This guard reads the SIGNED position and HALTs that case.

SAFETY
  - Idempotent: no-op once 'v19.34.285' markers exist.
  - Refuses to write unless ALL THREE hunks match exactly once.
  - Timestamped .bak + py_compile validation w/ auto-restore.
  - Hunk text is base64-embedded => byte-exact.

USAGE
  python3 apply_naked_sweep_flip_guard_v285.py
  python3 apply_naked_sweep_flip_guard_v285.py --repo /home/spark-1a60/Trading-and-Analysis-Platform
  python3 apply_naked_sweep_flip_guard_v285.py --dry-run
"""
import argparse
import base64
import os
import py_compile
import shutil
import sys
import time

MARKER = "v19.34.285"

_B64 = {
    "HA_OLD": "bG9nZ2VyID0gbG9nZ2luZy5nZXRMb2dnZXIoX19uYW1lX18pCgoKY2xhc3MgQm90TW9kZShzdHIsIEVudW0pOgo=",
    "HA_NEW": "bG9nZ2VyID0gbG9nZ2luZy5nZXRMb2dnZXIoX19uYW1lX18pCgoKIyDilIDilIAgdjE5LjM0LjI4NSDigJQgbmFrZWQtc3dlZXAgZmxpcCBndWFyZCAoZGlyZWN0aW9uLWF3YXJlKSDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKIyBUaGUgdjIzNSBwcm90ZWN0aXZlLXF0eSBjbGFtcCAoY2xhbXBfcHJvdGVjdGl2ZV9xdHkgKyBsaXZlX3Bvc2l0aW9uX2Ficykgb25seQojIGNvbXBhcmVzIE1BR05JVFVERVMg4oCUIGl0IGRpc2NhcmRzIHRoZSBTSUdOIG9mIHRoZSBsaXZlIElCIHBvc2l0aW9uLiBTbyB3aGVuIGEKIyB0cmFja2VkIHBvc2l0aW9uIGRlc3luY3Mgb3Zlcm5pZ2h0IGFuZCBJQiBlbmRzIHVwIEZMQVQgb3Igb24gdGhlIE9QUE9TSVRFIHNpZGUKIyAoQ1JNIG92ZXJuaWdodC1uYWtlZC1mbGlwIGluY2lkZW50KSwgdGhlIG5ha2VkLXN3ZWVwIHJlaXNzdWVzIGEgZnVsbC1zaXplIEVYSVQKIyAoU0VMTCBmb3IgYSBsb25nIC8gQlVZIGZvciBhIHNob3J0KSB0aGF0LCBvbiB0cmlnZ2VyLCBvdmVyc2VsbHMvb3ZlcmJ1eXMgcGFzdAojIHplcm8gYW5kIGNyZWF0ZXMgYSBOQUtFRCBmbGlwcGVkIHBvc2l0aW9uLiBUaGlzIGRlY2lkZXMsIHBlciBuYWtlZCB0cmFkZSwKIyB3aGV0aGVyIHJlaXNzdWluZyB0aGUgcHJvdGVjdGl2ZSBicmFja2V0IGlzIHNhZmUgZ2l2ZW4gdGhlIFNJR05FRCBsaXZlIElCCiMgcG9zaXRpb24uIChBIHNhbWUtc2lkZSBwYXJ0aWFsIOKAlCAwIDwgaGVsZCA8IHJzIOKAlCBzdGlsbCAncHJvY2VlZCdzOyB0aGUgdjIzNQojIG1hZ25pdHVkZSBjbGFtcCBpbnNpZGUgYXR0YWNoX29jYV9zdG9wX3RhcmdldCBzaHJpbmtzIHRoZSBvcmRlciBjb3JyZWN0bHkuKQpkZWYgX25ha2VkX3N3ZWVwX2ZsaXBfZGVjaXNpb24oZGlyZWN0aW9uX3ZhbHVlLCBib3RfcmVtYWluaW5nX3NoYXJlcywKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGliX3NpZ25lZF9xdHksIHBvc2l0aW9uc19hdmFpbGFibGUpOgogICAgIiIiUmV0dXJuICdza2lwX3VudmVyaWZpYWJsZScgfCAnaGFsdF9mbGF0X29yX29wcG9zaXRlJyB8ICdwcm9jZWVkJy4KCiAgICAtIGRpcmVjdGlvbl92YWx1ZTogJ2xvbmcnIHwgJ3Nob3J0JyAodGhlIGJvdCB0cmFkZSdzIHNpZGUpCiAgICAtIGJvdF9yZW1haW5pbmdfc2hhcmVzOiBzaGFyZXMgdGhlIGJvdCB0aGlua3MgaXQgaG9sZHMgKD4gMCkKICAgIC0gaWJfc2lnbmVkX3F0eTogbGl2ZSBJQiBuZXQgcG9zaXRpb24gZm9yIHRoZSBzeW1ib2wgKHNpZ25lZDsgKyBsb25nIC8gLQogICAgICBzaG9ydCksIG9yIE5vbmUgd2hlbiB0aGUgc3ltYm9sIGlzIGFic2VudCBmcm9tIGFuIG90aGVyd2lzZS1wcmVzZW50IHNuYXBzaG90CiAgICAtIHBvc2l0aW9uc19hdmFpbGFibGU6IEZhbHNlIHdoZW4gSUIgcG9zaXRpb24gZGF0YSBjb3VsZG4ndCBiZSByZWFkIHRoaXMgY3ljbGUKICAgICIiIgogICAgaWYgbm90IHBvc2l0aW9uc19hdmFpbGFibGU6CiAgICAgICAgcmV0dXJuICJza2lwX3VudmVyaWZpYWJsZSIKICAgIGlzX2xvbmcgPSBzdHIoZGlyZWN0aW9uX3ZhbHVlIG9yICJsb25nIikubG93ZXIoKSAhPSAic2hvcnQiCiAgICBzaWduZWQgPSAwLjAgaWYgaWJfc2lnbmVkX3F0eSBpcyBOb25lIGVsc2UgZmxvYXQoaWJfc2lnbmVkX3F0eSkKICAgIHNhbWVfc2lkZV9xdHkgPSBzaWduZWQgaWYgaXNfbG9uZyBlbHNlIC1zaWduZWQKICAgIGlmIHNhbWVfc2lkZV9xdHkgPD0gMDoKICAgICAgICAjIElCIGlzIGZsYXQgT1Igb24gdGhlIG9wcG9zaXRlIHNpZGUg4oCUIGFueSBleGl0IHJlaXNzdWUgd291bGQgZmxpcCBuYWtlZC4KICAgICAgICByZXR1cm4gImhhbHRfZmxhdF9vcl9vcHBvc2l0ZSIKICAgIHJldHVybiAicHJvY2VlZCIKCgpjbGFzcyBCb3RNb2RlKHN0ciwgRW51bSk6Cg==",
    "HB_OLD": "ICAgICAgICBsaXZlX29yZGVyX2lkcyA9IHNldCgpCiAgICAgICAgZm9yIG8gaW4gKGliX29yZGVycyBvciBbXSk6CiAgICAgICAgICAgIGZvciBrIGluICgiaWJfb3JkZXJfaWQiLCAib3JkZXJfaWQiLCAib3JkZXJJZCIsICJwZXJtX2lkIiwgImlkIik6CiAgICAgICAgICAgICAgICB2ID0gby5nZXQoaykgaWYgaXNpbnN0YW5jZShvLCBkaWN0KSBlbHNlIE5vbmUKICAgICAgICAgICAgICAgIGlmIHYgaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICAgICAgbGl2ZV9vcmRlcl9pZHMuYWRkKHN0cih2KSkK",
    "HB_NEW": "ICAgICAgICBsaXZlX29yZGVyX2lkcyA9IHNldCgpCiAgICAgICAgZm9yIG8gaW4gKGliX29yZGVycyBvciBbXSk6CiAgICAgICAgICAgIGZvciBrIGluICgiaWJfb3JkZXJfaWQiLCAib3JkZXJfaWQiLCAib3JkZXJJZCIsICJwZXJtX2lkIiwgImlkIik6CiAgICAgICAgICAgICAgICB2ID0gby5nZXQoaykgaWYgaXNpbnN0YW5jZShvLCBkaWN0KSBlbHNlIE5vbmUKICAgICAgICAgICAgICAgIGlmIHYgaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICAgICAgbGl2ZV9vcmRlcl9pZHMuYWRkKHN0cih2KSkKCiAgICAgICAgIyDilIDilIAgdjE5LjM0LjI4NSDigJQgZmxpcC1ndWFyZDogc2lnbmVkIGxpdmUgSUIgcG9zaXRpb25zIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICAgICAgICMgQnVpbGQgYSBTSUdORUQgcGVyLXN5bWJvbCBJQiBuZXQtcG9zaXRpb24gbWFwIHNvIGEgbmFrZWQgcmVpc3N1ZSBjYW4KICAgICAgICAjIGJlIHJlZnVzZWQgd2hlbiBJQiBpcyBmbGF0L29wcG9zaXRlIGZvciB0aGUgc3ltYm9sICh3b3VsZCBmbGlwIHRoZQogICAgICAgICMgcG9zaXRpb24gbmFrZWQpLiBBbiBlbXB0eS91bnJlYWRhYmxlIHNuYXBzaG90ID0+IHVudmVyaWZpYWJsZSwgYW5kIHRoZQogICAgICAgICMgcGVyLXRyYWRlIGd1YXJkIHRoZW4gU0tJUFMgcmVpc3N1ZSBmb3IgdGhhdCBjeWNsZSAobmV2ZXIgcmVpc3N1ZXMgYW4KICAgICAgICAjIGV4aXQgaXQgY2FuJ3QgY29uZmlybSkuIFNhbWUgc291cmNlIHRoZSByZWNvbmNpbGVyIHVzZXMuCiAgICAgICAgaWJfc2lnbmVkX2J5X3N5bTogRGljdFtzdHIsIGZsb2F0XSA9IHt9CiAgICAgICAgaWJfcG9zaXRpb25zX2F2YWlsYWJsZSA9IEZhbHNlCiAgICAgICAgdHJ5OgogICAgICAgICAgICBmcm9tIHNlcnZpY2VzLm9ycGhhbl9ndGNfcmVjb25jaWxlciBpbXBvcnQgX2ZldGNoX2liX3Bvc2l0aW9uc19hc3luYwogICAgICAgICAgICBfaWJwb3MsIF9pYnBvc19zcmMgPSBhd2FpdCBfZmV0Y2hfaWJfcG9zaXRpb25zX2FzeW5jKCkKICAgICAgICAgICAgaWYgKF9pYnBvc19zcmMgb3Ige30pLmdldCgib2siKSBhbmQgX2licG9zOgogICAgICAgICAgICAgICAgaWJfcG9zaXRpb25zX2F2YWlsYWJsZSA9IFRydWUKICAgICAgICAgICAgICAgIGZvciBfcCBpbiBfaWJwb3M6CiAgICAgICAgICAgICAgICAgICAgX3BzeW0gPSAoX3AuZ2V0KCJzeW1ib2wiKSBvciAiIikudXBwZXIoKQogICAgICAgICAgICAgICAgICAgIGlmIG5vdCBfcHN5bToKICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIGliX3NpZ25lZF9ieV9zeW1bX3BzeW1dID0gKAogICAgICAgICAgICAgICAgICAgICAgICAgICAgaWJfc2lnbmVkX2J5X3N5bS5nZXQoX3BzeW0sIDAuMCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgICsgZmxvYXQoX3AuZ2V0KCJwb3NpdGlvbiIpIG9yIDApCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICBleGNlcHQgKFR5cGVFcnJvciwgVmFsdWVFcnJvcik6CiAgICAgICAgICAgICAgICAgICAgICAgIHBhc3MKICAgICAgICAgICAgcmVzdWx0WyJmbGlwX2d1YXJkX3Bvc2l0aW9uc19hdmFpbGFibGUiXSA9IGliX3Bvc2l0aW9uc19hdmFpbGFibGUKICAgICAgICAgICAgcmVzdWx0WyJmbGlwX2d1YXJkX3Bvc2l0aW9uc19zb3VyY2UiXSA9IChfaWJwb3Nfc3JjIG9yIHt9KS5nZXQoInRpZXIiKQogICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgX2ZnZXJyOgogICAgICAgICAgICByZXN1bHRbImZsaXBfZ3VhcmRfcG9zaXRpb25zX2F2YWlsYWJsZSJdID0gRmFsc2UKICAgICAgICAgICAgcHJpbnQoCiAgICAgICAgICAgICAgICBmIlt2MTkuMzQuMjg1IGZsaXAtZ3VhcmRdIElCIHBvc2l0aW9uIGZldGNoIGZhaWxlZCAoY29udGludWluZyAiCiAgICAgICAgICAgICAgICBmImFzIHVudmVyaWZpYWJsZSk6IHtfZmdlcnJ9IiwgZmx1c2g9VHJ1ZSwKICAgICAgICAgICAgKQo=",
    "HC_OLD": "ICAgICAgICAgICAgICAgIHJlc3VsdFsibmFrZWRfZm91bmQiXSArPSAxCiAgICAgICAgICAgICAgICBzeW0gPSBnZXRhdHRyKHRyYWRlLCAic3ltYm9sIiwgIj8iKQogICAgICAgICAgICAgICAgcHJpbnQoCiAgICAgICAgICAgICAgICAgICAgZiJbdjEyNyBuYWtlZC1zd2VlcF0ge3N5bX0ge3RpZH0gTkFLRUQg4oCUICIKICAgICAgICAgICAgICAgICAgICBmInN0b3BfaWQ9e3N0b3BfaWRfc3RyIXJ9IHNpbXVsYXRlZD17aXNfc2ltdWxhdGVkfSAiCiAgICAgICAgICAgICAgICAgICAgZiJub3QgaW4ge2xlbihsaXZlX29yZGVyX2lkcyl9IGxpdmUgb3JkZXJzLiAiCiAgICAgICAgICAgICAgICAgICAgZiJFbWVyZ2VuY3kgcmUtaXNzdWUuIiwKICAgICAgICAgICAgICAgICAgICBmbHVzaD1UcnVlLAogICAgICAgICAgICAgICAgKQoK",
    "HC_NEW": "ICAgICAgICAgICAgICAgIHJlc3VsdFsibmFrZWRfZm91bmQiXSArPSAxCiAgICAgICAgICAgICAgICBzeW0gPSBnZXRhdHRyKHRyYWRlLCAic3ltYm9sIiwgIj8iKQogICAgICAgICAgICAgICAgcHJpbnQoCiAgICAgICAgICAgICAgICAgICAgZiJbdjEyNyBuYWtlZC1zd2VlcF0ge3N5bX0ge3RpZH0gTkFLRUQg4oCUICIKICAgICAgICAgICAgICAgICAgICBmInN0b3BfaWQ9e3N0b3BfaWRfc3RyIXJ9IHNpbXVsYXRlZD17aXNfc2ltdWxhdGVkfSAiCiAgICAgICAgICAgICAgICAgICAgZiJub3QgaW4ge2xlbihsaXZlX29yZGVyX2lkcyl9IGxpdmUgb3JkZXJzLiAiCiAgICAgICAgICAgICAgICAgICAgZiJFbWVyZ2VuY3kgcmUtaXNzdWUuIiwKICAgICAgICAgICAgICAgICAgICBmbHVzaD1UcnVlLAogICAgICAgICAgICAgICAgKQoKICAgICAgICAgICAgICAgICMg4pSA4pSAIHYxOS4zNC4yODUg4oCUIGZsaXAtZ3VhcmQgKGRpcmVjdGlvbi1hd2FyZSkg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAgICAgICAgICAgICAgICAjIEJlZm9yZSByZWlzc3VpbmcgdGhlIHByb3RlY3RpdmUgRVhJVCBicmFja2V0LCB2ZXJpZnkgSUIncwogICAgICAgICAgICAgICAgIyBTSUdORUQgcG9zaXRpb24uIElmIElCIGlzIGZsYXQvb3Bwb3NpdGUgKG9yIHVudmVyaWZpYWJsZSksCiAgICAgICAgICAgICAgICAjIHJlaXNzdWluZyB3b3VsZCBvdmVyc2VsbC9vdmVyYnV5IGFuZCBmbGlwIHRoZSBwb3NpdGlvbiBuYWtlZC4KICAgICAgICAgICAgICAgIF9kaXJfb2JqMjg1ID0gZ2V0YXR0cih0cmFkZSwgImRpcmVjdGlvbiIsIE5vbmUpCiAgICAgICAgICAgICAgICBfZGlyX3YyODUgPSBnZXRhdHRyKAogICAgICAgICAgICAgICAgICAgIF9kaXJfb2JqMjg1LCAidmFsdWUiLAogICAgICAgICAgICAgICAgICAgIHN0cihfZGlyX29iajI4NSkgaWYgX2Rpcl9vYmoyODUgZWxzZSAibG9uZyIsCiAgICAgICAgICAgICAgICApLmxvd2VyKCkKICAgICAgICAgICAgICAgIF9pYl9zaWduZWQyODUgPSAoCiAgICAgICAgICAgICAgICAgICAgaWJfc2lnbmVkX2J5X3N5bS5nZXQoc3ltLnVwcGVyKCkpCiAgICAgICAgICAgICAgICAgICAgaWYgaWJfcG9zaXRpb25zX2F2YWlsYWJsZSBlbHNlIE5vbmUKICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIF9kZWNpc2lvbjI4NSA9IF9uYWtlZF9zd2VlcF9mbGlwX2RlY2lzaW9uKAogICAgICAgICAgICAgICAgICAgIF9kaXJfdjI4NSwgcnMsIF9pYl9zaWduZWQyODUsIGliX3Bvc2l0aW9uc19hdmFpbGFibGUsCiAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICBpZiBfZGVjaXNpb24yODUgIT0gInByb2NlZWQiOgogICAgICAgICAgICAgICAgICAgIGlmIF9kZWNpc2lvbjI4NSA9PSAic2tpcF91bnZlcmlmaWFibGUiOgogICAgICAgICAgICAgICAgICAgICAgICByZXN1bHQuc2V0ZGVmYXVsdCgiZmxpcF9ndWFyZF9za2lwcGVkX3VudmVyaWZpYWJsZSIsIDApCiAgICAgICAgICAgICAgICAgICAgICAgIHJlc3VsdFsiZmxpcF9ndWFyZF9za2lwcGVkX3VudmVyaWZpYWJsZSJdICs9IDEKICAgICAgICAgICAgICAgICAgICAgICAgX3BoYXNlMjg1ID0gIm5ha2VkX3N3ZWVwX2ZsaXBfZ3VhcmRfc2tpcCIKICAgICAgICAgICAgICAgICAgICAgICAgX3JlYXNvbjI4NSA9ICJpYl9wb3NpdGlvbl91bnZlcmlmaWFibGUiCiAgICAgICAgICAgICAgICAgICAgICAgIHByaW50KAogICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJbdjE5LjM0LjI4NSBmbGlwLWd1YXJkXSB7c3ltfSB7dGlkfSBTS0lQIHJlaXNzdWUg4oCUICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiSUIgcG9zaXRpb24gZGF0YSB1bmF2YWlsYWJsZSB0aGlzIGN5Y2xlOyByZWZ1c2luZyAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmInVudmVyaWZpYWJsZSBleGl0IHJlaXNzdWUuIiwgZmx1c2g9VHJ1ZSwKICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgIGVsc2U6ICAjIGhhbHRfZmxhdF9vcl9vcHBvc2l0ZQogICAgICAgICAgICAgICAgICAgICAgICByZXN1bHQuc2V0ZGVmYXVsdCgiZmxpcF9ndWFyZF9oYWx0cyIsIDApCiAgICAgICAgICAgICAgICAgICAgICAgIHJlc3VsdFsiZmxpcF9ndWFyZF9oYWx0cyJdICs9IDEKICAgICAgICAgICAgICAgICAgICAgICAgX3BoYXNlMjg1ID0gIm5ha2VkX3N3ZWVwX2hhbHRfbm9faWJfcG9zaXRpb24iCiAgICAgICAgICAgICAgICAgICAgICAgIF9yZWFzb24yODUgPSAiaWJfZmxhdF9vcl9vcHBvc2l0ZSIKICAgICAgICAgICAgICAgICAgICAgICAgdHJ5OgogICAgICAgICAgICAgICAgICAgICAgICAgICAgdHJhZGUuZGVzeW5jX2ZsYWdnZWQgPSBUcnVlCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB0cmFkZS5kZXN5bmNfcmVhc29uID0gImliX2ZsYXRfb3Jfb3Bwb3NpdGVfdjI4NSIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHRyYWRlLmRlc3luY19kZXRlY3RlZF9hdCA9ICgKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRldGltZS5ub3codGltZXpvbmUudXRjKS5pc29mb3JtYXQoKQogICAgICAgICAgICAgICAgICAgICAgICAgICAgKQogICAgICAgICAgICAgICAgICAgICAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgICAgICAgICAgICAgICAgICBwcmludCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiW3YxOS4zNC4yODUgZmxpcC1ndWFyZF0ge3N5bX0ge3RpZH0gSEFSRC1IQUxUICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYicmVpc3N1ZSDigJQgYm90IHRoaW5rcyB7X2Rpcl92Mjg1fSB7cnN9c2ggYnV0IElCIG5ldD0iCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmInsoX2liX3NpZ25lZDI4NSBpZiBfaWJfc2lnbmVkMjg1IGlzIG5vdCBOb25lIGVsc2UgMCk6Ky4wZn0uICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiUmVpc3N1ZSB3b3VsZCBmbGlwIG5ha2VkLiBGbGFnZ2VkIGRlc3luYyBmb3IgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJyZWNvbmNpbGVyLiIsIGZsdXNoPVRydWUsCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgICAgIGF3YWl0IF9wZXJzaXN0X2xpZmVjeWNsZV9ldmVudCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGJvdD1zZWxmLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgZXZlbnQ9ewogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJwaGFzZSI6IF9waGFzZTI4NSwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3VjY2VzcyI6IEZhbHNlLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJ0cmFkZV9pZCI6IHRpZCwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAic3ltYm9sIjogc3ltLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJyZWFzb24iOiBfcmVhc29uMjg1LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJib3RfcmVtYWluaW5nX3NoYXJlcyI6IHJzLAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJpYl9wb3NpdGlvbl9xdHkiOiBfaWJfc2lnbmVkMjg1LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICJkaXJlY3Rpb24iOiBfZGlyX3YyODUsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB9LAogICAgICAgICAgICAgICAgICAgICAgICApCiAgICAgICAgICAgICAgICAgICAgZXhjZXB0IEV4Y2VwdGlvbiBhcyBfcGxlMjg1OgogICAgICAgICAgICAgICAgICAgICAgICBwcmludCgKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiW3YxOS4zNC4yODUgZmxpcC1ndWFyZF0gbGlmZWN5Y2xlIHBlcnNpc3QgZmFpbGVkOiAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBmIntfcGxlMjg1fSIsIGZsdXNoPVRydWUsCiAgICAgICAgICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICAgICAgIyDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKCg==",
}

def _d(k):
    return base64.b64decode(_B64[k]).decode("utf-8")

HUNKS = [
    ("Hunk A (flip-decision helper)", _d("HA_OLD"), _d("HA_NEW")),
    ("Hunk B (signed IB positions)", _d("HB_OLD"), _d("HB_NEW")),
    ("Hunk C (per-trade flip guard)", _d("HC_OLD"), _d("HC_NEW")),
]


def log(m):
    print(f"[v285-applier] {m}", flush=True)


def find_repo(explicit):
    if explicit:
        return explicit
    here = os.path.abspath(os.path.dirname(__file__))
    for base in (here, os.getcwd(), os.path.expanduser("~/Trading-and-Analysis-Platform")):
        cur = base
        for _ in range(6):
            if os.path.isfile(os.path.join(cur, "backend", "services", "trading_bot_service.py")):
                return cur
            parent = os.path.dirname(cur)
            if parent == cur:
                break
            cur = parent
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--repo", default=None)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    repo = find_repo(args.repo)
    if not repo:
        log("ERROR: could not locate backend/services/trading_bot_service.py. Pass --repo.")
        return 2
    path = os.path.join(repo, "backend", "services", "trading_bot_service.py")
    log(f"file: {path}")

    with open(path, "r", encoding="utf-8") as fh:
        content = fh.read()

    if MARKER in content:
        log(f"Already applied ('{MARKER}' present). No changes made.")
        return 0

    for name, old, _new in HUNKS:
        n = content.count(old)
        if n != 1:
            log(f"ERROR: {name} anchor matched {n} times (expected 1). Aborting - nothing written.")
            return 3
    for name, old, new in HUNKS:
        content = content.replace(old, new, 1)
        log(f"staged: {name}")
    if content.count(MARKER) < 1:
        log("ERROR: post-apply marker missing. Aborting.")
        return 4

    if args.dry_run:
        log("DRY-RUN: all three hunks match and would apply cleanly. Nothing written.")
        return 0

    bak = f"{path}.bak.v285.{time.strftime('%Y%m%d-%H%M%S')}"
    shutil.copy2(path, bak)
    log(f"backup: {bak}")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    try:
        py_compile.compile(path, doraise=True)
        log("py_compile OK.")
    except py_compile.PyCompileError as e:
        log(f"ERROR: py_compile failed: {e}; restoring backup.")
        shutil.copy2(bak, path)
        return 5

    log("SUCCESS - v19.34.285 naked-sweep flip guard applied.")
    log("Restart the backend service to activate.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
