#!/usr/bin/env python3
"""
apply_gate_funnel_v286.py  (SentCom v19.34.286, rebuild b — DGX-anchored)

Idempotent applier for the alert->trade GATE near-miss funnel in symbol-trace.
Rebuilt against the live DGX scanner.py (targeted hunks, drift-proof).

WHAT IT DOES
  backend/routers/scanner.py :: /symbol-trace
    - adds _drop_margin() + _summarize_symbol_drops() helpers
    - joins the symbol's `trade_drops` (the UNIFIED sink for every gate kill +
      margin context) into the trace
    - verdict names the killing gate + margin (e.g.
      "killed at gate 'tqs_too_low' (8x) - TQS 52 < min 60")
    - adds `gate_funnel` to the response + `trade_drops` to today_counts
  backend/scripts/probe_symbol_day.py : prints the gate funnel
  backend/tests/test_gate_funnel_v286.py : 12 unit tests

SAFETY
  - Idempotent: no-op once 'v19.34.286' present.
  - Each hunk must match its DGX anchor exactly once or the file is skipped clean.
  - Timestamped .bak per file + py_compile w/ auto-restore.
  - Pure-additive observability: NO trading-logic change.

USAGE
  python3 apply_gate_funnel_v286.py --dry-run --repo ~/Trading-and-Analysis-Platform
  python3 apply_gate_funnel_v286.py --repo ~/Trading-and-Analysis-Platform
"""
import argparse, base64, os, py_compile, shutil, sys, time
MARKER="v19.34.286"
_B64={
    "H1_OLD": "QHJvdXRlci5nZXQoIi9zeW1ib2wtdHJhY2UiKQpkZWYgZ2V0X3N5bWJvbF90cmFjZShzeW1ib2w6IHN0cik6Cg==",
    "H1_NEW": "IyDilIDilIAgdjE5LjM0LjI4NiDigJQgZ2F0ZSBuZWFyLW1pc3MgZnVubmVsIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAojIHN5bWJvbC10cmFjZSBoaXN0b3JpY2FsbHkgY291bnRlZCB0aGUgbGVnYWN5IGByZWplY3Rpb25fZXZlbnRzYCBjb2xsZWN0aW9uCiMgKGVmZmVjdGl2ZWx5IGFsd2F5cyAwKSBhbmQgc3RvcHBlZCBhdCAiU0NBTk5FRCAmIEFMRVJURUQg4oCUIE4gYWxlcnRzOyBjaGVjayB0aGUKIyBnYXRlcyIuIFRoZSBhY3R1YWwgYWxlcnTihpJ0cmFkZSBraWxsIHJlYXNvbnMgYWxsIGxhbmQgaW4gYHRyYWRlX2Ryb3BzYCAoQk9USAojIHJlY29yZF90cmFkZV9kcm9wIEFORCByZWNvcmRfcmVqZWN0aW9uIHBlcnNpc3QgdGhlcmUsIHdpdGggbWFyZ2luIGNvbnRleHQpLgojIFRoZXNlIGhlbHBlcnMgam9pbiB0aGF0IHBlci1zeW1ib2wgc28gdGhlIHRyYWNlIGFuc3dlcnMgKndoaWNoKiBnYXRlIGF0ZSB0aGUKIyBhbGVydHMgYW5kICpieSBob3cgbXVjaCogKGUuZy4gInRxc190b29fbG93OiBUUVMgNTIgPCBtaW4gNjAsIG1pc3NlZCBieSA4IikuCmRlZiBfZHJvcF9tYXJnaW4oZ2F0ZSwgY3R4KToKICAgICIiIkNvbXBhY3QgJ2J5IGhvdyBtdWNoJyBzdHJpbmcgZm9yIGEgZ2F0ZSdzIG1hcmdpbiBmcm9tIGl0cyBkcm9wIGNvbnRleHQuCiAgICBSZXR1cm5zIE5vbmUgd2hlbiBubyBudW1lcmljIG1hcmdpbiBpcyBhdmFpbGFibGUgZm9yIHRoZSBnYXRlLiBOZXZlciByYWlzZXMuIiIiCiAgICBjdHggPSBjdHggb3Ige30KCiAgICBkZWYgX2YoKmtleXMpOgogICAgICAgIGZvciBrIGluIGtleXM6CiAgICAgICAgICAgIHYgPSBjdHguZ2V0KGspCiAgICAgICAgICAgIGlmIHYgaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIGZsb2F0KHYpCiAgICAgICAgICAgICAgICBleGNlcHQgKFR5cGVFcnJvciwgVmFsdWVFcnJvcik6CiAgICAgICAgICAgICAgICAgICAgcGFzcwogICAgICAgIHJldHVybiBOb25lCgogICAgdHJ5OgogICAgICAgIGlmIGdhdGUgPT0gInRxc190b29fbG93IjoKICAgICAgICAgICAgdHFzLCBtbiA9IF9mKCJ0cXMiLCAidHFzX3Njb3JlIiksIF9mKCJtaW5fdHFzIikKICAgICAgICAgICAgaWYgdHFzIGlzIG5vdCBOb25lIGFuZCBtbiBpcyBub3QgTm9uZToKICAgICAgICAgICAgICAgIHJldHVybiBmIlRRUyB7dHFzOi4wZn0gPCBtaW4ge21uOi4wZn0gKG1pc3NlZCBieSB7bW4gLSB0cXM6LjBmfSkiCiAgICAgICAgaWYgZ2F0ZSBpbiAoInJyX2JlbG93X21pbiIsICJycl9iZWxvd19taW5fdjE5XzM0Xzg4Iik6CiAgICAgICAgICAgIHJyLCBtbiA9IF9mKCJycl9yYXRpbyIsICJyaXNrX3Jld2FyZCIpLCBfZigibWluX3JlcXVpcmVkIiwgImdsb2JhbF9taW4iKQogICAgICAgICAgICBpZiByciBpcyBub3QgTm9uZSBhbmQgbW4gaXMgbm90IE5vbmU6CiAgICAgICAgICAgICAgICByZXR1cm4gZiJSOlIge3JyOi4yZn0gPCBtaW4ge21uOi4yZn0iCiAgICAgICAgaWYgZ2F0ZSA9PSAic21hcnRfZmlsdGVyX3NraXAiOgogICAgICAgICAgICB3ciA9IF9mKCJ3aW5fcmF0ZSIsICJzdHJhdGVneV93aW5fcmF0ZSIpCiAgICAgICAgICAgIGlmIHdyIGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgcmV0dXJuIGYid2luLXJhdGUge3dyICogMTAwOi4wZn0lIiBpZiB3ciA8PSAxIGVsc2UgZiJ3aW4tcmF0ZSB7d3I6LjBmfSUiCiAgICAgICAgaWYgZ2F0ZSBpbiAoInN5bWJvbF9kaXJlY3Rpb25fb3Blbl9jYXBfdjEyMyIsICJzeW1ib2xfZXhwb3N1cmVfc2F0dXJhdGVkIiwKICAgICAgICAgICAgICAgICAgICAibWF4X29wZW5fcG9zaXRpb25zIik6CiAgICAgICAgICAgIGN1ciA9IF9mKCJjdXJyZW50IiwgIm9wZW5fY291bnQiLCAiY3VycmVudF9leHBvc3VyZSIpCiAgICAgICAgICAgIGNhcCA9IF9mKCJjYXAiLCAibWF4IiwgImxpbWl0IiwgIm1heF9vcGVuX3Bvc2l0aW9ucyIpCiAgICAgICAgICAgIGlmIGN1ciBpcyBub3QgTm9uZSBhbmQgY2FwIGlzIG5vdCBOb25lOgogICAgICAgICAgICAgICAgcmV0dXJuIGYie2N1cjouMGZ9L3tjYXA6LjBmfSBjYXAiCiAgICAgICAgaWYgZ2F0ZSA9PSAicG9zdF9zdG9wX2Nvb2xkb3duIjoKICAgICAgICAgICAgbGVmdCA9IF9mKCJjb29sZG93bl9zZWNvbmRzX2xlZnQiLCAic2Vjb25kc19sZWZ0IikKICAgICAgICAgICAgaWYgbGVmdCBpcyBub3QgTm9uZToKICAgICAgICAgICAgICAgIHJldHVybiBmIntsZWZ0Oi4wZn1zIGNvb2xkb3duIGxlZnQiCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHJldHVybiBOb25lCiAgICByZXR1cm4gTm9uZQoKCmRlZiBfc3VtbWFyaXplX3N5bWJvbF9kcm9wcyhkcm9wcyk6CiAgICAiIiJBZ2dyZWdhdGUgYSBzeW1ib2wncyBgdHJhZGVfZHJvcHNgIHJvd3MgaW50byBhIHBlci1nYXRlIGZ1bm5lbC4KICAgIFB1cmUgKyB1bml0LXRlc3RhYmxlLiBgZHJvcHNgIGluIGFueSBvcmRlcjsgZWFjaCBpcyBhIGRpY3Qgd2l0aCBrZXlzCiAgICBnYXRlIC8gc2V0dXBfdHlwZSAvIHJlYXNvbiAvIGNvbnRleHQgLyB0cy4iIiIKICAgIGJ5X2dhdGUgPSB7fQogICAgZm9yIGQgaW4gZHJvcHM6CiAgICAgICAgZyA9IGQuZ2V0KCJnYXRlIikgb3IgInVua25vd24iCiAgICAgICAgZSA9IGJ5X2dhdGUuZ2V0KGcpCiAgICAgICAgaWYgZSBpcyBOb25lOgogICAgICAgICAgICBlID0geyJjb3VudCI6IDAsICJsYXN0X3RzIjogTm9uZSwgImxhc3RfcmVhc29uIjogTm9uZSwKICAgICAgICAgICAgICAgICAibWFyZ2luIjogTm9uZSwgInNldHVwcyI6IHNldCgpfQogICAgICAgICAgICBieV9nYXRlW2ddID0gZQogICAgICAgIGVbImNvdW50Il0gKz0gMQogICAgICAgIHRzID0gZC5nZXQoInRzIikKICAgICAgICBpZiBlWyJsYXN0X3RzIl0gaXMgTm9uZSBvciAodHMgYW5kIHRzID4gZVsibGFzdF90cyJdKToKICAgICAgICAgICAgZVsibGFzdF90cyJdID0gdHMKICAgICAgICAgICAgZVsibGFzdF9yZWFzb24iXSA9ICgoZC5nZXQoInJlYXNvbiIpIG9yICIiKVs6MTYwXSkgb3IgTm9uZQogICAgICAgICAgICBtID0gX2Ryb3BfbWFyZ2luKGcsIGQuZ2V0KCJjb250ZXh0IikpCiAgICAgICAgICAgIGlmIG06CiAgICAgICAgICAgICAgICBlWyJtYXJnaW4iXSA9IG0KICAgICAgICBzdCA9IGQuZ2V0KCJzZXR1cF90eXBlIikKICAgICAgICBpZiBzdDoKICAgICAgICAgICAgZVsic2V0dXBzIl0uYWRkKHN0KQogICAgb3V0ID0ge30KICAgIGZvciBnLCBlIGluIGJ5X2dhdGUuaXRlbXMoKToKICAgICAgICBlWyJzZXR1cHMiXSA9IHNvcnRlZChlWyJzZXR1cHMiXSkKICAgICAgICBvdXRbZ10gPSBlCiAgICBmaXJzdF9raWxsaW5nID0gKG1heChvdXQuaXRlbXMoKSwga2V5PWxhbWJkYSBrdjoga3ZbMV1bImNvdW50Il0pWzBdCiAgICAgICAgICAgICAgICAgICAgIGlmIG91dCBlbHNlIE5vbmUpCiAgICByZXR1cm4gewogICAgICAgICJ0b3RhbCI6IHN1bShlWyJjb3VudCJdIGZvciBlIGluIG91dC52YWx1ZXMoKSksCiAgICAgICAgImZpcnN0X2tpbGxpbmdfZ2F0ZSI6IGZpcnN0X2tpbGxpbmcsCiAgICAgICAgImJ5X2dhdGUiOiBvdXQsCiAgICB9CgoKQHJvdXRlci5nZXQoIi9zeW1ib2wtdHJhY2UiKQpkZWYgZ2V0X3N5bWJvbF90cmFjZShzeW1ib2w6IHN0cik6Cg==",
    "H2_OLD": "ICAgIHRvZGF5ID0gbm93LnN0cmZ0aW1lKCIlWS0lbS0lZCIpCiAgICBjb3VudHMgPSB7fQogICAgdHJ5OgogICAgICAgIGRiID0gc2MuZGIKICAgICAgICBmb3IgYyBpbiAoImxpdmVfYWxlcnRzIiwgImFsZXJ0cyIsICJzaGFkb3dfZGVjaXNpb25zIiwgInJlamVjdGlvbl9ldmVudHMiLCAiYm90X3RyYWRlcyIpOgogICAgICAgICAgICBjb3VudHNbY10gPSBpbnQoZGJbY10uY291bnRfZG9jdW1lbnRzKAogICAgICAgICAgICAgICAgeyJzeW1ib2wiOiBzeW0sICJjcmVhdGVkX2F0IjogeyIkZ3RlIjogdG9kYXl9fSkpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKCiAgICAjIDYpIFBsYWluLWxhbmd1YWdlIHZlcmRpY3QuCg==",
    "H2_NEW": "ICAgIHRvZGF5ID0gbm93LnN0cmZ0aW1lKCIlWS0lbS0lZCIpCiAgICBjb3VudHMgPSB7fQogICAgdHJ5OgogICAgICAgIGRiID0gc2MuZGIKICAgICAgICBmb3IgYyBpbiAoImxpdmVfYWxlcnRzIiwgImFsZXJ0cyIsICJzaGFkb3dfZGVjaXNpb25zIiwgInJlamVjdGlvbl9ldmVudHMiLCAiYm90X3RyYWRlcyIpOgogICAgICAgICAgICBjb3VudHNbY10gPSBpbnQoZGJbY10uY291bnRfZG9jdW1lbnRzKAogICAgICAgICAgICAgICAgeyJzeW1ib2wiOiBzeW0sICJjcmVhdGVkX2F0IjogeyIkZ3RlIjogdG9kYXl9fSkpCiAgICBleGNlcHQgRXhjZXB0aW9uOgogICAgICAgIHBhc3MKCiAgICAjIDViKSB2MTkuMzQuMjg2IOKAlCBhbGVydOKGknRyYWRlIEdBVEUgZnVubmVsIGZyb20gYHRyYWRlX2Ryb3BzYCAodGhlIHVuaWZpZWQKICAgICMgc2luayB3aGVyZSBldmVyeSBnYXRlJ3Mga2lsbCBsYW5kcykuIFRoaXMgaXMgd2hlcmUgYWxlcnRzIGFjdHVhbGx5IGRpZTsKICAgICMgYHJlamVjdGlvbl9ldmVudHNgIGFib3ZlIGlzIHRoZSBsZWdhY3kvbmVhci1lbXB0eSBjb2xsZWN0aW9uIGtlcHQgb25seSBmb3IKICAgICMgYmFjay1jb21wYXQgY291bnRzLiBgdHNgIGlzIGEgZnVsbCBJU08gc3RyaW5nIOKGkiBsZXhpY2FsID49IG9uIHRoZSBkYXkgd29ya3MuCiAgICBnYXRlX2Z1bm5lbCA9IHsidG90YWwiOiAwLCAiZmlyc3Rfa2lsbGluZ19nYXRlIjogTm9uZSwgImJ5X2dhdGUiOiB7fX0KICAgIHRyeToKICAgICAgICBkcm9wcyA9IGxpc3Qoc2MuZGJbInRyYWRlX2Ryb3BzIl0uZmluZCgKICAgICAgICAgICAgeyJzeW1ib2wiOiBzeW0sICJ0cyI6IHsiJGd0ZSI6IHRvZGF5fX0sCiAgICAgICAgICAgIHsiX2lkIjogMCwgImdhdGUiOiAxLCAic2V0dXBfdHlwZSI6IDEsICJyZWFzb24iOiAxLAogICAgICAgICAgICAgImNvbnRleHQiOiAxLCAidHMiOiAxfSwKICAgICAgICApLnNvcnQoInRzIiwgLTEpLmxpbWl0KDIwMCkpCiAgICAgICAgZ2F0ZV9mdW5uZWwgPSBfc3VtbWFyaXplX3N5bWJvbF9kcm9wcyhkcm9wcykKICAgICAgICBjb3VudHNbInRyYWRlX2Ryb3BzIl0gPSBnYXRlX2Z1bm5lbFsidG90YWwiXQogICAgZXhjZXB0IEV4Y2VwdGlvbjoKICAgICAgICBwYXNzCgogICAgIyA2KSBQbGFpbi1sYW5ndWFnZSB2ZXJkaWN0Lgo=",
    "H3_OLD": "ICAgICAgICBlbGlmIHN0ID09ICJzY2FubmVkIjoKICAgICAgICAgICAgaWYgY291bnRzLmdldCgibGl2ZV9hbGVydHMiLCAwKSA+IDA6CiAgICAgICAgICAgICAgICB2ZXJkaWN0ID0gKGYiU0NBTk5FRCAmIEFMRVJURUQg4oCUIHtjb3VudHMuZ2V0KCdsaXZlX2FsZXJ0cycpfSBhbGVydChzKSB0b2RheTsgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAiaWYgbm8gdHJhZGUsIGNoZWNrIHByaW9yaXR5L3RhcGUvVFFTIGdhdGUgb3IgcmVqZWN0aW9uLWV2ZW50cyIpCiAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICB2ZXJkaWN0ID0gKCJTQ0FOTkVELCBOTyBBTEVSVCDigJQgcGFzc2VkIEFEVitSVk9MIHByZS1maWx0ZXJzIGJ1dCBubyBkZXRlY3RvciAiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICJmaXJlZCAodGhlIHNldHVwIHBhdHRlcm4gd2Fzbid0IHByZXNlbnQgcGVyIHRoZSBib3QncyByZWFkKSIp",
    "H3_NEW": "ICAgICAgICBlbGlmIHN0ID09ICJzY2FubmVkIjoKICAgICAgICAgICAgaWYgY291bnRzLmdldCgibGl2ZV9hbGVydHMiLCAwKSA+IDA6CiAgICAgICAgICAgICAgICBpZiBjb3VudHMuZ2V0KCJib3RfdHJhZGVzIiwgMCkgPiAwOgogICAgICAgICAgICAgICAgICAgIHZlcmRpY3QgPSAoZiJTQ0FOTkVEICYgQUxFUlRFRCAmIFRSQURFRCDigJQge2NvdW50cy5nZXQoJ2xpdmVfYWxlcnRzJyl9ICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiYWxlcnQocykg4oaSIHtjb3VudHMuZ2V0KCdib3RfdHJhZGVzJyl9IHRyYWRlKHMpIHRvZGF5IOKckyIpCiAgICAgICAgICAgICAgICBlbGlmIGdhdGVfZnVubmVsWyJ0b3RhbCJdID4gMDoKICAgICAgICAgICAgICAgICAgICBnID0gZ2F0ZV9mdW5uZWxbImZpcnN0X2tpbGxpbmdfZ2F0ZSJdCiAgICAgICAgICAgICAgICAgICAgZ2UgPSBnYXRlX2Z1bm5lbFsiYnlfZ2F0ZSJdLmdldChnLCB7fSkKICAgICAgICAgICAgICAgICAgICBtYXJnaW5fc3RyID0gZiIg4oCUIHtnZS5nZXQoJ21hcmdpbicpfSIgaWYgZ2UuZ2V0KCJtYXJnaW4iKSBlbHNlICIiCiAgICAgICAgICAgICAgICAgICAgdmVyZGljdCA9IChmIlNDQU5ORUQgJiBBTEVSVEVEIGJ1dCAwIFRSQURFUyDigJQge2NvdW50cy5nZXQoJ2xpdmVfYWxlcnRzJyl9ICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiYWxlcnQocykga2lsbGVkIGF0IGdhdGUgJ3tnfScgKHtnZS5nZXQoJ2NvdW50Jyl9w5cpe21hcmdpbl9zdHJ9IikKICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgdmVyZGljdCA9IChmIlNDQU5ORUQgJiBBTEVSVEVELCAwIHRyYWRlcywgTk8gZ2F0ZS1kcm9wIGxvZ2dlZCDigJQgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZiJ7Y291bnRzLmdldCgnbGl2ZV9hbGVydHMnKX0gYWxlcnQocykgZmlsdGVyZWQgUFJFLWV2YWwgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZiIocHJpb3JpdHkgLyBhdXRvX2V4ZWN1dGVfZWxpZ2libGUgLyB0YXBlIGludGFrZSkuICIKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGYiRHJvcCBpcyBoYXBwZW5pbmcgYmVmb3JlIGFueSBpbnN0cnVtZW50ZWQgZ2F0ZS4iKQogICAgICAgICAgICBlbHNlOgogICAgICAgICAgICAgICAgdmVyZGljdCA9ICgiU0NBTk5FRCwgTk8gQUxFUlQg4oCUIHBhc3NlZCBBRFYrUlZPTCBwcmUtZmlsdGVycyBidXQgbm8gZGV0ZWN0b3IgIgogICAgICAgICAgICAgICAgICAgICAgICAgICAiZmlyZWQgKHRoZSBzZXR1cCBwYXR0ZXJuIHdhc24ndCBwcmVzZW50IHBlciB0aGUgYm90J3MgcmVhZCkiKQ==",
    "H4_OLD": "ICAgICAgICAibGFzdF9ldmFsIjogbGFzdF9ldmFsLAogICAgICAgICJ0b2RheV9jb3VudHMiOiBjb3VudHMsCiAgICAgICAgInRpbWVzdGFtcCI6IG5vdy5pc29mb3JtYXQoKSwKICAgIH0=",
    "H4_NEW": "ICAgICAgICAibGFzdF9ldmFsIjogbGFzdF9ldmFsLAogICAgICAgICJ0b2RheV9jb3VudHMiOiBjb3VudHMsCiAgICAgICAgImdhdGVfZnVubmVsIjogZ2F0ZV9mdW5uZWwsCiAgICAgICAgInRpbWVzdGFtcCI6IG5vdy5pc29mb3JtYXQoKSwKICAgIH0=",
    "P_OLD": "ICAgIHByaW50KGYidG9kYXkgICA6IGxpdmVfYWxlcnRzPXt0Yy5nZXQoJ2xpdmVfYWxlcnRzJywgMCl9ICAiCiAgICAgICAgICBmImFsZXJ0cz17dGMuZ2V0KCdhbGVydHMnLCAwKX0gIHNoYWRvdz17dGMuZ2V0KCdzaGFkb3dfZGVjaXNpb25zJywgMCl9ICAiCiAgICAgICAgICBmInJlamVjdGlvbnM9e3RjLmdldCgncmVqZWN0aW9uX2V2ZW50cycsIDApfSAgYm90X3RyYWRlcz17dGMuZ2V0KCdib3RfdHJhZGVzJywgMCl9IikKICAgIHByaW50KCkK",
    "P_NEW": "ICAgIHByaW50KGYidG9kYXkgICA6IGxpdmVfYWxlcnRzPXt0Yy5nZXQoJ2xpdmVfYWxlcnRzJywgMCl9ICAiCiAgICAgICAgICBmImFsZXJ0cz17dGMuZ2V0KCdhbGVydHMnLCAwKX0gIHNoYWRvdz17dGMuZ2V0KCdzaGFkb3dfZGVjaXNpb25zJywgMCl9ICAiCiAgICAgICAgICBmInJlamVjdGlvbnM9e3RjLmdldCgncmVqZWN0aW9uX2V2ZW50cycsIDApfSAgYm90X3RyYWRlcz17dGMuZ2V0KCdib3RfdHJhZGVzJywgMCl9IikKICAgICMgdjE5LjM0LjI4NiDigJQgYWxlcnTihpJ0cmFkZSBnYXRlIGZ1bm5lbCAod2hpY2ggZ2F0ZSBhdGUgdGhlIGFsZXJ0cywgYnkgaG93IG11Y2gpCiAgICBnZiA9IGRhdGEuZ2V0KCJnYXRlX2Z1bm5lbCIsIHt9KSBvciB7fQogICAgYmcgPSBnZi5nZXQoImJ5X2dhdGUiLCB7fSkgb3Ige30KICAgIGZrID0gZiIgIGZpcnN0X2tpbGxpbmc9e2dmLmdldCgnZmlyc3Rfa2lsbGluZ19nYXRlJyl9IiBpZiBnZi5nZXQoImZpcnN0X2tpbGxpbmdfZ2F0ZSIpIGVsc2UgIiIKICAgIHByaW50KGYiZ2F0ZXMgICA6IHtnZi5nZXQoJ3RvdGFsJywgMCl9IHRyYWRlX2Ryb3AocykgdG9kYXl7Zmt9IikKICAgIGZvciBnLCBlIGluIHNvcnRlZChiZy5pdGVtcygpLCBrZXk9bGFtYmRhIGt2OiBrdlsxXS5nZXQoImNvdW50IiwgMCksIHJldmVyc2U9VHJ1ZSk6CiAgICAgICAgbWFyZ2luID0gZiIgIFt7ZS5nZXQoJ21hcmdpbicpfV0iIGlmIGUuZ2V0KCJtYXJnaW4iKSBlbHNlICIiCiAgICAgICAgc2V0dXBzID0gIiwiLmpvaW4oKGUuZ2V0KCJzZXR1cHMiKSBvciBbXSlbOjNdKQogICAgICAgIHByaW50KGYiICAgLSB7Z30gw5d7ZS5nZXQoJ2NvdW50Jyl9e21hcmdpbn0iCiAgICAgICAgICAgICAgKyAoZiIgIHNldHVwcz17c2V0dXBzfSIgaWYgc2V0dXBzIGVsc2UgIiIpKQogICAgICAgIGlmIGUuZ2V0KCJsYXN0X3JlYXNvbiIpOgogICAgICAgICAgICBwcmludChmIiAgICAgICBsYXN0OiB7ZS5nZXQoJ2xhc3RfcmVhc29uJyl9IikKICAgIHByaW50KCkK",
    "TEST": "IiIiCnRlc3RfZ2F0ZV9mdW5uZWxfdjI4Ni5weSDigJQgZ3VhcmRzIHRoZSBzeW1ib2wtdHJhY2UgYWxlcnTihpJ0cmFkZSBnYXRlIGZ1bm5lbC4KClRoZSBmdW5uZWwgam9pbnMgYSBzeW1ib2wncyBgdHJhZGVfZHJvcHNgIHJvd3Mgc28gdGhlIHRyYWNlIGFuc3dlcnMgV0hJQ0ggZ2F0ZQphdGUgdGhlIGFsZXJ0cyBhbmQgQlkgSE9XIE1VQ0guIFB1cmUtZnVuY3Rpb24gdGVzdHMgKG5vIE1vbmdvIC8gbm8gc2Nhbm5lcikuCiIiIgppbXBvcnQgb3MKaW1wb3J0IHN5cwoKc3lzLnBhdGguaW5zZXJ0KDAsIG9zLnBhdGguZGlybmFtZShvcy5wYXRoLmRpcm5hbWUob3MucGF0aC5hYnNwYXRoKF9fZmlsZV9fKSkpKQoKZnJvbSByb3V0ZXJzLnNjYW5uZXIgaW1wb3J0IF9kcm9wX21hcmdpbiwgX3N1bW1hcml6ZV9zeW1ib2xfZHJvcHMgICMgbm9xYTogRTQwMgoKCmNsYXNzIFRlc3REcm9wTWFyZ2luOgogICAgZGVmIHRlc3RfdHFzX3Rvb19sb3dfbWFyZ2luKHNlbGYpOgogICAgICAgIG0gPSBfZHJvcF9tYXJnaW4oInRxc190b29fbG93IiwgeyJ0cXMiOiA1MiwgIm1pbl90cXMiOiA2MH0pCiAgICAgICAgYXNzZXJ0IG0gPT0gIlRRUyA1MiA8IG1pbiA2MCAobWlzc2VkIGJ5IDgpIgoKICAgIGRlZiB0ZXN0X3JyX2JlbG93X21pbl9tYXJnaW4oc2VsZik6CiAgICAgICAgbSA9IF9kcm9wX21hcmdpbigicnJfYmVsb3dfbWluIiwgeyJycl9yYXRpbyI6IDEuMTksICJtaW5fcmVxdWlyZWQiOiAxLjV9KQogICAgICAgIGFzc2VydCBtID09ICJSOlIgMS4xOSA8IG1pbiAxLjUwIgoKICAgIGRlZiB0ZXN0X3NtYXJ0X2ZpbHRlcl9mcmFjdGlvbmFsX3dpbnJhdGUoc2VsZik6CiAgICAgICAgYXNzZXJ0IF9kcm9wX21hcmdpbigic21hcnRfZmlsdGVyX3NraXAiLCB7Indpbl9yYXRlIjogMC4xN30pID09ICJ3aW4tcmF0ZSAxNyUiCgogICAgZGVmIHRlc3Rfc21hcnRfZmlsdGVyX3BlcmNlbnRfd2lucmF0ZShzZWxmKToKICAgICAgICBhc3NlcnQgX2Ryb3BfbWFyZ2luKCJzbWFydF9maWx0ZXJfc2tpcCIsIHsid2luX3JhdGUiOiAxN30pID09ICJ3aW4tcmF0ZSAxNyUiCgogICAgZGVmIHRlc3Rfb3Blbl9jYXBfbWFyZ2luKHNlbGYpOgogICAgICAgIGFzc2VydCBfZHJvcF9tYXJnaW4oIm1heF9vcGVuX3Bvc2l0aW9ucyIsIHsiY3VycmVudCI6IDUsICJtYXgiOiA1fSkgPT0gIjUvNSBjYXAiCgogICAgZGVmIHRlc3RfY29vbGRvd25fbWFyZ2luKHNlbGYpOgogICAgICAgIGFzc2VydCBfZHJvcF9tYXJnaW4oInBvc3Rfc3RvcF9jb29sZG93biIsIHsiY29vbGRvd25fc2Vjb25kc19sZWZ0IjogMjQwfSkgPT0gIjI0MHMgY29vbGRvd24gbGVmdCIKCiAgICBkZWYgdGVzdF91bmtub3duX2dhdGVfcmV0dXJuc19ub25lKHNlbGYpOgogICAgICAgIGFzc2VydCBfZHJvcF9tYXJnaW4oImFjY291bnRfZ3VhcmQiLCB7ImZvbyI6IDF9KSBpcyBOb25lCgogICAgZGVmIHRlc3RfbWlzc2luZ19jb250ZXh0X3JldHVybnNfbm9uZShzZWxmKToKICAgICAgICBhc3NlcnQgX2Ryb3BfbWFyZ2luKCJ0cXNfdG9vX2xvdyIsIHt9KSBpcyBOb25lCiAgICAgICAgYXNzZXJ0IF9kcm9wX21hcmdpbigidHFzX3Rvb19sb3ciLCBOb25lKSBpcyBOb25lCgogICAgZGVmIHRlc3RfYmFkX3ZhbHVlc19kb250X3JhaXNlKHNlbGYpOgogICAgICAgIGFzc2VydCBfZHJvcF9tYXJnaW4oInRxc190b29fbG93IiwgeyJ0cXMiOiAieCIsICJtaW5fdHFzIjogTm9uZX0pIGlzIE5vbmUKCgpjbGFzcyBUZXN0U3VtbWFyaXplRHJvcHM6CiAgICBkZWYgdGVzdF9lbXB0eShzZWxmKToKICAgICAgICBzID0gX3N1bW1hcml6ZV9zeW1ib2xfZHJvcHMoW10pCiAgICAgICAgYXNzZXJ0IHMgPT0geyJ0b3RhbCI6IDAsICJmaXJzdF9raWxsaW5nX2dhdGUiOiBOb25lLCAiYnlfZ2F0ZSI6IHt9fQoKICAgIGRlZiB0ZXN0X2FnZ3JlZ2F0ZXNfYW5kX3JhbmtzKHNlbGYpOgogICAgICAgIGRyb3BzID0gWwogICAgICAgICAgICB7ImdhdGUiOiAidHFzX3Rvb19sb3ciLCAic2V0dXBfdHlwZSI6ICJzcXVlZXplIiwgInJlYXNvbiI6ICJsb3cgdHFzIiwKICAgICAgICAgICAgICJjb250ZXh0IjogeyJ0cXMiOiA1MiwgIm1pbl90cXMiOiA2MH0sICJ0cyI6ICIyMDI2LTA2LTA1VDE3OjAwOjAwIn0sCiAgICAgICAgICAgIHsiZ2F0ZSI6ICJ0cXNfdG9vX2xvdyIsICJzZXR1cF90eXBlIjogInZ3YXBfZmFkZSIsICJyZWFzb24iOiAibG93IHRxcyAyIiwKICAgICAgICAgICAgICJjb250ZXh0IjogeyJ0cXMiOiA0OCwgIm1pbl90cXMiOiA2MH0sICJ0cyI6ICIyMDI2LTA2LTA1VDE4OjAwOjAwIn0sCiAgICAgICAgICAgIHsiZ2F0ZSI6ICJycl9iZWxvd19taW4iLCAic2V0dXBfdHlwZSI6ICJzcXVlZXplIiwgInJlYXNvbiI6ICJyciBsb3ciLAogICAgICAgICAgICAgImNvbnRleHQiOiB7InJyX3JhdGlvIjogMS4xLCAibWluX3JlcXVpcmVkIjogMS41fSwgInRzIjogIjIwMjYtMDYtMDVUMTc6MzA6MDAifSwKICAgICAgICBdCiAgICAgICAgcyA9IF9zdW1tYXJpemVfc3ltYm9sX2Ryb3BzKGRyb3BzKQogICAgICAgIGFzc2VydCBzWyJ0b3RhbCJdID09IDMKICAgICAgICBhc3NlcnQgc1siZmlyc3Rfa2lsbGluZ19nYXRlIl0gPT0gInRxc190b29fbG93IiAgIyAyIHZzIDEKICAgICAgICB0cXMgPSBzWyJieV9nYXRlIl1bInRxc190b29fbG93Il0KICAgICAgICBhc3NlcnQgdHFzWyJjb3VudCJdID09IDIKICAgICAgICAjIG1hcmdpbiB0YWtlbiBmcm9tIHRoZSBMQVRFU1QgKDE4OjAwKSBkcm9wCiAgICAgICAgYXNzZXJ0IHRxc1sibWFyZ2luIl0gPT0gIlRRUyA0OCA8IG1pbiA2MCAobWlzc2VkIGJ5IDEyKSIKICAgICAgICBhc3NlcnQgdHFzWyJsYXN0X3JlYXNvbiJdID09ICJsb3cgdHFzIDIiCiAgICAgICAgYXNzZXJ0IHRxc1sic2V0dXBzIl0gPT0gWyJzcXVlZXplIiwgInZ3YXBfZmFkZSJdCgogICAgZGVmIHRlc3RfdW5rbm93bl9nYXRlX2xhYmVsKHNlbGYpOgogICAgICAgIHMgPSBfc3VtbWFyaXplX3N5bWJvbF9kcm9wcyhbeyJnYXRlIjogTm9uZSwgInRzIjogIjIwMjYtMDYtMDVUMDE6MDA6MDAifV0pCiAgICAgICAgYXNzZXJ0ICJ1bmtub3duIiBpbiBzWyJieV9nYXRlIl0KICAgICAgICBhc3NlcnQgc1siZmlyc3Rfa2lsbGluZ19nYXRlIl0gPT0gInVua25vd24iCg==",
}
def _d(k): return base64.b64decode(_B64[k]).decode("utf-8")
def log(m): print(f"[v286-applier] {m}", flush=True)

SCANNER_HUNKS=[("H1",_d("H1_OLD"),_d("H1_NEW")),("H2",_d("H2_OLD"),_d("H2_NEW")),
               ("H3",_d("H3_OLD"),_d("H3_NEW")),("H4",_d("H4_OLD"),_d("H4_NEW"))]
PROBE_HUNKS=[("P",_d("P_OLD"),_d("P_NEW"))]

def find_repo(x):
    if x: return x
    here=os.path.abspath(os.path.dirname(__file__))
    for b in (here,os.getcwd(),os.path.expanduser("~/Trading-and-Analysis-Platform")):
        c=b
        for _ in range(6):
            if os.path.isfile(os.path.join(c,"backend","routers","scanner.py")): return c
            p=os.path.dirname(c)
            if p==c: break
            c=p
    return None

def patch(path, hunks, dry):
    with open(path,encoding="utf-8") as fh: content=fh.read()
    if MARKER in content:
        log(f"already patched: {os.path.basename(path)}"); return True
    for n,o,_nw in hunks:
        cnt=content.count(o)
        if cnt!=1:
            log(f"ERROR: {os.path.basename(path)} hunk {n} matched {cnt} (expected 1). Aborting file."); return False
    for n,o,nw in hunks: content=content.replace(o,nw,1)
    if dry:
        log(f"DRY-RUN ok: {os.path.basename(path)} ({len(hunks)} hunks match)"); return True
    bak=f"{path}.bak.v286.{time.strftime('%Y%m%d-%H%M%S')}"; shutil.copy2(path,bak); log(f"backup: {bak}")
    with open(path,"w",encoding="utf-8") as fh: fh.write(content)
    try: py_compile.compile(path,doraise=True); log(f"py_compile OK: {os.path.basename(path)}")
    except py_compile.PyCompileError as e:
        log(f"ERROR py_compile {os.path.basename(path)}: {e}; restoring"); shutil.copy2(bak,path); return False
    return True

def main():
    a=argparse.ArgumentParser(); a.add_argument("--repo",default=None); a.add_argument("--dry-run",action="store_true")
    args=a.parse_args()
    repo=find_repo(args.repo)
    if not repo: log("ERROR: repo root not found. Pass --repo."); return 2
    log(f"repo: {repo}")
    scanner=os.path.join(repo,"backend","routers","scanner.py")
    probe=os.path.join(repo,"backend","scripts","probe_symbol_day.py")
    test=os.path.join(repo,"backend","tests","test_gate_funnel_v286.py")
    if not patch(scanner,SCANNER_HUNKS,args.dry_run): return 3
    if not patch(probe,PROBE_HUNKS,args.dry_run): return 4
    if args.dry_run:
        log("DRY-RUN: all hunks match + test would be written. Nothing changed."); return 0
    os.makedirs(os.path.dirname(test),exist_ok=True)
    with open(test,"w",encoding="utf-8") as fh: fh.write(_d("TEST"))
    try: py_compile.compile(test,doraise=True); log(f"wrote + compiled: {test}")
    except py_compile.PyCompileError as e: log(f"ERROR test py_compile: {e}"); return 5
    log("SUCCESS - v19.34.286 gate funnel applied.")
    log("Tests:  .venv/bin/python -m pytest backend/tests/test_gate_funnel_v286.py -q")
    log("Then ./start_backend.sh --force and re-probe: probe_symbol_day.py NVDA")
    return 0

if __name__=="__main__": sys.exit(main())
