#!/usr/bin/env python3
"""
patch_v352_backside_cheatsheet.py  (AGENTS.md 2.2 -- function-anchored patcher)

WHAT: re-aligns enhanced_scanner._check_backside to the OFFICIAL SMB Back$ide cheat sheet.
      v348 anchored the stop at the DEEP flush LOD (R:R << 1). v352 uses the doctrine's TIGHT
      stop = .02 below the MOST RECENT HIGHER LOW, requires a HIGHER-LOW + HIGHER-HIGH rising
      structure, price above the 9-EMA but below VWAP, recovered > halfway between LOD and VWAP,
      target = VWAP, one-and-done (1/day), 10:00-13:30 ET window, R:R >= 1.0.
WHY : cheat-sheet-faithful + far better edge. v352 14d native-1min replay: 63% win, winsorAvg
      +0.70R, medR +1.11R, avg R:R 4.8 to VWAP (vs v348 +0.28R). Cheat sheet: 50-60% win, ~1.4:1.
      Anchored to the CURRENT live backside (== v348 bytes). 1-min bars from ib_historical_data
      (IB-only) via self.technical_service._get_intraday_bars_from_db(sym,"1 min",60).

DRIFT NOTE: FUNCTION-ANCHORED. Asserts live whole-file SHA == DGX baseline AND the exact v348
      _check_backside bytes present (count==1), replaces, asserts new func SHA, py_compiles the
      whole file before writing. backup + func-SHA guards cover the (paste-limited) whole POST.

Usage (repo root, DGX):
  .venv/bin/python backend/scripts/patch_v352_backside_cheatsheet.py --check
  .venv/bin/python backend/scripts/patch_v352_backside_cheatsheet.py --apply
  .venv/bin/python backend/scripts/patch_v352_backside_cheatsheet.py --rollback
Then: pytest backend/tests/test_v352_backside.py -q ; commit ; ./start_backend.sh --force
"""
import base64, hashlib, sys, shutil, os, py_compile, tempfile

FILE = "backend/services/enhanced_scanner.py"
DGX_WHOLE_PRE = "e772deda3d2dcb84affe1edcf8257999b3129c6ce178c34041c94b0846b3cc92"
PRE_FUNC_SHA  = "2f6f4f6100c8a49399a130349b08cd0f1967568cf06b68f4838cb90302df2b4d"
POST_FUNC_SHA = "e7d323085deecf03b351dacc5c3191668b821c860815155d7bbebed99662b2d1"
OLD_B64 = "ICAgIGFzeW5jIGRlZiBfY2hlY2tfYmFja3NpZGUoc2VsZiwgc3ltYm9sOiBzdHIsIHNuYXBzaG90LCB0YXBlOiBUYXBlUmVhZGluZykgLT4gT3B0aW9uYWxbTGl2ZUFsZXJ0XToKICAgICAgICAiIiJCYWNrJGlkZSBcdTIwMTQgc2hhbGxvdyBWV0FQLXJlY292ZXJ5IHNuYXBiYWNrICh2MTkuMzQuMzQ4IHJlZGVzaWduLCBMT05HLW9ubHkpLgoKICAgICAgICBGaXJlcyBvbiB0aGUgVFJJR0dFUiwgbm90IGEgZGlzdF9mcm9tX3Z3YXAgU1RBVEU6IGFmdGVyIGEgU0hBTExPVyBkaXAgQkVMT1cgc2Vzc2lvbgogICAgICAgIFZXQVAgKHRoZSBbMC4zJSwgMS4wJSkgYmFuZCB0aGF0IHZ3YXBfZmFkZSBcdTIwMTQgd2hpY2ggZmxvb3JzIGF0IDEuMCUgXHUyMDE0IHN0cnVjdHVyYWxseQogICAgICAgIGNhbm5vdCBzZXJ2ZSksIHByaWNlIG11c3QgcmVjbGFpbSB0aGUgOS1FTUEgYW5kIGEgMS1taW4gZG91YmxlLWJhci1ISUdILWJyZWFrIHNuYXBiYWNrCiAgICAgICAgcHJpbnRzIHdpdGhpbiArMS4uKzQgYmFycyBvZiB0aGUgZGlwLWxvdywgc25hcHBpbmcgYmFjayBVUCB0byBWV0FQLiBWYWxpZGF0ZWQgK0VWIG9uIGEKICAgICAgICAxNGQgcmlzay1jb250cm9sbGVkIG5hdGl2ZS0xbWluIHJlcGxheSAodjM0NzogMC0wLjUlIGJhbmQgd2luOTMlLyswLjExUiwgMC41LTElIGJhbmQKICAgICAgICB3aW44OCUvKzAuNDFSOyBuPTMyLzMzIFVOSVFVRSB2cyB2d2FwX2ZhZGUgXHUyMDE0IGEgZGlzdGluY3Qgc2hhbGxvdy1kaXAgcmVjb3ZlcnkgZWRnZSwKICAgICAgICBOT1QgYSBkdXBsaWNhdGUpLiBSZXF1aXJlcyBzdG9wID49IDEuMCUgb2YgZW50cnkgKHRoZSBtaW4tcmlzayBmbG9vciB0aGF0IGdhdGVkIH45NiUgb2YKICAgICAgICB0aGUgbG9vc2Ugc3RhdGUgZmlyZXMpICsgUlZPTCA+PSAxLjIgKyBwcmljZSBhYm92ZSB0aGUgOS1FTUEgKyAyIGZpcmVzL2RheSBwZXIgc3ltYm9sLgogICAgICAgICIiIgogICAgICAgIERJUF9GTE9PUiA9IDAuMwogICAgICAgIERJUF9DRUlMID0gMS4wICAgICAgICAgICMgPj0gMS4wJSBpcyB2d2FwX2ZhZGUncyBiYW5kIFx1MjAxNCBrZWVwIGJhY2tzaWRlIGNvbXBsZW1lbnRhcnkgKHplcm8gb3ZlcmxhcCkKICAgICAgICBUUklHR0VSX1dJTiA9IDQKICAgICAgICBBQ0NFTCA9IDEuMwogICAgICAgIE1JTl9SVk9MID0gMS4yCiAgICAgICAgTUlOX1JJU0tfUENUID0gMS4wCgogICAgICAgIGlmIG5vdCBnZXRhdHRyKHNuYXBzaG90LCAiYWJvdmVfZW1hOSIsIEZhbHNlKToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICB0cyA9IGdldGF0dHIoc2VsZiwgInRlY2huaWNhbF9zZXJ2aWNlIiwgTm9uZSkKICAgICAgICBpZiB0cyBpcyBOb25lOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIGJhcnMgPSB0cy5fZ2V0X2ludHJhZGF5X2JhcnNfZnJvbV9kYihzeW1ib2wsICIxIG1pbiIsIDYwKQogICAgICAgIGlmIG5vdCBiYXJzIG9yIGxlbihiYXJzKSA8IDU6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgcnZvbCA9IGZsb2F0KGdldGF0dHIoc25hcHNob3QsICJydm9sIiwgMC4wKSBvciAwLjApCiAgICAgICAgaWYgcnZvbCA8IE1JTl9SVk9MOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIHZ3YXAgPSBmbG9hdChnZXRhdHRyKHNuYXBzaG90LCAidndhcCIsIDAuMCkgb3IgMC4wKQogICAgICAgIGlmIHZ3YXAgPD0gMDoKICAgICAgICAgICAgcmV0dXJuIE5vbmUKCiAgICAgICAgY2FwcyA9IGdldGF0dHIoc2VsZiwgIl9iYWNrc2lkZV9kYWlseV9jYXBzIiwgTm9uZSkKICAgICAgICBpZiBjYXBzIGlzIE5vbmU6CiAgICAgICAgICAgIGNhcHMgPSBzZWxmLl9iYWNrc2lkZV9kYWlseV9jYXBzID0ge30KICAgICAgICB0b2RheSA9IGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpLnN0cmZ0aW1lKCIlWS0lbS0lZCIpCgogICAgICAgIGRlZiBfbWVkaWFuKHhzKToKICAgICAgICAgICAgcyA9IHNvcnRlZCh4cykKICAgICAgICAgICAgbiA9IGxlbihzKQogICAgICAgICAgICBpZiBuID09IDA6CiAgICAgICAgICAgICAgICByZXR1cm4gMC4wCiAgICAgICAgICAgIHJldHVybiBzW24gLy8gMl0gaWYgbiAlIDIgZWxzZSAoc1tuIC8vIDIgLSAxXSArIHNbbiAvLyAyXSkgLyAyLjAKCiAgICAgICAgaSA9IGxlbihiYXJzKSAtIDEKICAgICAgICBsYXN0ID0gYmFyc1tpXQogICAgICAgIHJhbmdlcyA9IFsoYlsiaGlnaCJdIC0gYlsibG93Il0pIGZvciBiIGluIGJhcnNbOmldCiAgICAgICAgICAgICAgICAgIGlmIGIuZ2V0KCJoaWdoIikgaXMgbm90IE5vbmUgYW5kIGIuZ2V0KCJsb3ciKSBpcyBub3QgTm9uZV0KICAgICAgICBtZWRfciA9IF9tZWRpYW4ocmFuZ2VzKQoKICAgICAgICBsb3dzID0gWyhqLCBiWyJsb3ciXSkgZm9yIGosIGIgaW4gZW51bWVyYXRlKGJhcnMpIGlmIGIuZ2V0KCJsb3ciKSBpcyBub3QgTm9uZV0KICAgICAgICBpZiBsb3dzOgogICAgICAgICAgICBsb2QgPSBtaW4odiBmb3IgXywgdiBpbiBsb3dzKQogICAgICAgICAgICBsb2RfaWR4ID0gbWF4KGogZm9yIGosIHYgaW4gbG93cyBpZiB2ID09IGxvZCkKICAgICAgICAgICAgZGlwID0gKHZ3YXAgLSBsb2QpIC8gdndhcCAqIDEwMC4wCiAgICAgICAgICAgIGFjY2VsX29rID0gKG1lZF9yIDw9IDApIG9yICgoYmFyc1tsb2RfaWR4XVsiaGlnaCJdIC0gYmFyc1tsb2RfaWR4XVsibG93Il0pID49IEFDQ0VMICogbWVkX3IpCiAgICAgICAgICAgIGdyZWVuID0gbGFzdFsiY2xvc2UiXSA+IGxhc3RbIm9wZW4iXQogICAgICAgICAgICBjbGVhcnNfaGkgPSBpID49IDIgYW5kIGxhc3RbImhpZ2giXSA+IG1heChiYXJzW2kgLSAxXVsiaGlnaCJdLCBiYXJzW2kgLSAyXVsiaGlnaCJdKQogICAgICAgICAgICBpZiAoRElQX0ZMT09SIDw9IGRpcCA8IERJUF9DRUlMIGFuZCBhY2NlbF9vayBhbmQgZ3JlZW4gYW5kIGNsZWFyc19oaQogICAgICAgICAgICAgICAgICAgIGFuZCAxIDw9IChpIC0gbG9kX2lkeCkgPD0gVFJJR0dFUl9XSU4pOgogICAgICAgICAgICAgICAga2V5ID0gZiJ7c3ltYm9sfTp7dG9kYXl9OmxvbmciCiAgICAgICAgICAgICAgICBpZiBjYXBzLmdldChrZXksIDApID49IDI6CiAgICAgICAgICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICAgICAgICAgIGVudHJ5ID0gcm91bmQobWF4KGJhcnNbaSAtIDFdWyJoaWdoIl0sIGJhcnNbaSAtIDJdWyJoaWdoIl0pLCAyKQogICAgICAgICAgICAgICAgaWYgZW50cnkgPj0gdndhcDoKICAgICAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgICAgICAgICAgc3RvcF9sb3NzID0gcm91bmQobWluKGxvZCAtIDAuMDIsIHNuYXBzaG90LnN1cHBvcnQgLSAoc25hcHNob3QuYXRyICogMC4yNSkpLCAyKQogICAgICAgICAgICAgICAgcmlzayA9IGVudHJ5IC0gc3RvcF9sb3NzCiAgICAgICAgICAgICAgICBpZiByaXNrIDw9IDAgb3IgZW50cnkgPD0gMCBvciAocmlzayAvIGVudHJ5ICogMTAwLjApIDwgTUlOX1JJU0tfUENUOgogICAgICAgICAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgICAgICAgICB0YXJnZXRfMSA9IHJvdW5kKHZ3YXAsIDIpCiAgICAgICAgICAgICAgICByZXdhcmQgPSB0YXJnZXRfMSAtIGVudHJ5CiAgICAgICAgICAgICAgICByX211bHRpcGxlID0gcm91bmQocmV3YXJkIC8gcmlzaywgMikgaWYgcmlzayA+IDAgZWxzZSAyLjAKICAgICAgICAgICAgICAgIHByaW9yaXR5ID0gQWxlcnRQcmlvcml0eS5ISUdIIGlmIHRhcGUuY29uZmlybWF0aW9uX2Zvcl9sb25nIGVsc2UgQWxlcnRQcmlvcml0eS5NRURJVU0KICAgICAgICAgICAgICAgIGV2X2luZm8gPSAiIgogICAgICAgICAgICAgICAgaWYgImJhY2tzaWRlIiBpbiBzZWxmLl9zdHJhdGVneV9zdGF0czoKICAgICAgICAgICAgICAgICAgICBzdCA9IHNlbGYuX3N0cmF0ZWd5X3N0YXRzWyJiYWNrc2lkZSJdCiAgICAgICAgICAgICAgICAgICAgaWYgc3Qud2luX3JhdGUgPiAwOgogICAgICAgICAgICAgICAgICAgICAgICBldl9pbmZvID0gZiJIaXN0b3JpY2FsOiB7c3Qud2luX3JhdGU6LjAlfSB3aW4sIEVWIHtzdC5leHBlY3RlZF92YWx1ZV9yOi4yZn1SIgogICAgICAgICAgICAgICAgY2Fwc1trZXldID0gY2Fwcy5nZXQoa2V5LCAwKSArIDEKICAgICAgICAgICAgICAgIHRhcGVfdGFnID0gIlx1MjcxMyBUQVBFIiBpZiB0YXBlLmNvbmZpcm1hdGlvbl9mb3JfbG9uZyBlbHNlICIiCiAgICAgICAgICAgICAgICByZXR1cm4gTGl2ZUFsZXJ0KAogICAgICAgICAgICAgICAgICAgIGlkPWYiYmFja3NpZGVfe3N5bWJvbH1fe2RhdGV0aW1lLm5vdygpLnN0cmZ0aW1lKCclSCVNJVMnKX0iLAogICAgICAgICAgICAgICAgICAgIHN5bWJvbD1zeW1ib2wsCiAgICAgICAgICAgICAgICAgICAgc2V0dXBfdHlwZT0iYmFja3NpZGUiLAogICAgICAgICAgICAgICAgICAgIHN0cmF0ZWd5X25hbWU9IkJhY2skaWRlIFNjYWxwIChJTlQtMzIpIiwKICAgICAgICAgICAgICAgICAgICBkaXJlY3Rpb249ImxvbmciLAogICAgICAgICAgICAgICAgICAgIHByaW9yaXR5PXByaW9yaXR5LAogICAgICAgICAgICAgICAgICAgIGN1cnJlbnRfcHJpY2U9c25hcHNob3QuY3VycmVudF9wcmljZSwKICAgICAgICAgICAgICAgICAgICB0cmlnZ2VyX3ByaWNlPWVudHJ5LAogICAgICAgICAgICAgICAgICAgIHN0b3BfbG9zcz1zdG9wX2xvc3MsCiAgICAgICAgICAgICAgICAgICAgdGFyZ2V0PXRhcmdldF8xLAogICAgICAgICAgICAgICAgICAgIHJpc2tfcmV3YXJkPXJfbXVsdGlwbGUsCiAgICAgICAgICAgICAgICAgICAgdHJpZ2dlcl9wcm9iYWJpbGl0eT0wLjY1LAogICAgICAgICAgICAgICAgICAgIHdpbl9wcm9iYWJpbGl0eT0wLjczLAogICAgICAgICAgICAgICAgICAgIG1pbnV0ZXNfdG9fdHJpZ2dlcj0wLAogICAgICAgICAgICAgICAgICAgIGhlYWRsaW5lPWYiXFUwMDAxZjNhZiB7c3ltYm9sfSBCYWNrJGlkZSBzbmFwYmFjayBcdTIwMTQge2RpcDouMWZ9JSBkaXAgcmVjbGFpbSB0byBWV0FQIHt0YXBlX3RhZ30iLAogICAgICAgICAgICAgICAgICAgIHJlYXNvbmluZz1bCiAgICAgICAgICAgICAgICAgICAgICAgIGYiU2hhbGxvdyB7ZGlwOi4xZn0lIGRpcCBiZWxvdyBWV0FQICR7dndhcDouMmZ9IFx1MjE5MiAxLW1pbiBkb3VibGUtYmFyLWJyZWFrIHJlY2xhaW0iLAogICAgICAgICAgICAgICAgICAgICAgICBmIlNuYXBiYWNrIHtpIC0gbG9kX2lkeH0gYmFyKHMpIGFmdGVyIExPRCAke2xvZDouMmZ9IChmbHVzaCByYW5nZSA+PSB7QUNDRUw6Z314IG1lZGlhbiksIGFib3ZlIDktRU1BIiwKICAgICAgICAgICAgICAgICAgICAgICAgZiJSOlIgPSB7cl9tdWx0aXBsZTouMWZ9OjEgKFN0b3AgJHtzdG9wX2xvc3M6LjJmfSBiZWxvdyBMT0QsIFRhcmdldCBWV0FQICR7dGFyZ2V0XzE6LjJmfSkiLAogICAgICAgICAgICAgICAgICAgICAgICBmIlJWT0wge3J2b2w6LjFmfXggfCBUYXBlOiB7dGFwZS5vdmVyYWxsX3NpZ25hbC52YWx1ZX0iLAogICAgICAgICAgICAgICAgICAgICAgICBldl9pbmZvIGlmIGV2X2luZm8gZWxzZSAiU2hhbGxvdyBWV0FQLXJlY292ZXJ5ICh2MzQ3IHJlcGxheSArMC4yOFIsIDkxJSB3aW4sIDAuMy0xJSBiYW5kKSIsCiAgICAgICAgICAgICAgICAgICAgICAgICJFbnRyeTogZ3JlZW4gYmFyIHJlY2xhaW1lZCBwcmlvci0yIGhpZ2hzICgwLjMtMSUgYmFuZCwgY29tcGxlbWVudGFyeSB0byB2d2FwX2ZhZGUsIDIvZGF5IGNhcCkiLAogICAgICAgICAgICAgICAgICAgIF0sCiAgICAgICAgICAgICAgICAgICAgdGltZV93aW5kb3c9c2VsZi5fZ2V0X2N1cnJlbnRfdGltZV93aW5kb3coKS52YWx1ZSwKICAgICAgICAgICAgICAgICAgICBtYXJrZXRfcmVnaW1lPXNlbGYuX21hcmtldF9yZWdpbWUudmFsdWUsCiAgICAgICAgICAgICAgICAgICAgZXhwaXJlc19hdD0oZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykgKyB0aW1lZGVsdGEoaG91cnM9MSkpLmlzb2Zvcm1hdCgpCiAgICAgICAgICAgICAgICApCiAgICAgICAgcmV0dXJuIE5vbmUKICAgIAo="
NEW_B64 = "ICAgIGFzeW5jIGRlZiBfY2hlY2tfYmFja3NpZGUoc2VsZiwgc3ltYm9sOiBzdHIsIHNuYXBzaG90LCB0YXBlOiBUYXBlUmVhZGluZykgLT4gT3B0aW9uYWxbTGl2ZUFsZXJ0XToKICAgICAgICAiIiJCYWNrJGlkZSBcdTIwMTQgY2hlYXQtc2hlZXQtZmFpdGhmdWwgVldBUC1yZWNvdmVyeSBzY2FscCAodjE5LjM0LjM1MikuCgogICAgICAgIFJlLWFsaWduZWQgdG8gdGhlIE9GRklDSUFMIFNNQiBCYWNrJGlkZSBjaGVhdCBzaGVldCAodjM0OCB1c2VkIGEgREVFUCBmbHVzaC1sb3cgc3RvcAogICAgICAgIHdoaWNoIGNydXNoZWQgUjpSOyBkb2N0cmluZSB1c2VzIGEgVElHSFQgc3RvcCAuMDIgYmVsb3cgdGhlIE1PU1QgUkVDRU5UIEhJR0hFUiBMT1cpLgogICAgICAgIExPTkcgb25seS4gUmlzaW5nIHBoYXNlIGFmdGVyIGEgZGlzdGluY3QgbG93OiBhIEhJR0hFUiBMT1cgKHJlY2VudCBwdWxsYmFjayBsb3cgPiB0aGUKICAgICAgICBzZXNzaW9uIExPRCkgcGx1cyBhIEhJR0hFUiBISUdIIChncmVlbiAxLW1pbiBkb3VibGUtYmFyLWhpZ2ggYnJlYWsgPSAiYnJlYWsgb2YgYSAxLW1pbgogICAgICAgIGJhciBmcm9tIGNvbnNvbGlkYXRpb24sIHBheSB0aGUgb2ZmZXIgb24gdGhlIGJyZWFrIiksIHByaWNlIGhvbGRpbmcgQUJPVkUgdGhlIDktRU1BIGJ1dAogICAgICAgIHN0aWxsIEJFTE9XIFZXQVAsIHJlY292ZXJlZCBNT1JFIHRoYW4gaGFsZndheSBiZXR3ZWVuIExPRCBhbmQgVldBUC4gU1RPUCA9IHJlY2VudCBoaWdoZXIKICAgICAgICBsb3cgLSAwLjAyICh0aWdodCkuIFRBUkdFVCA9IFZXQVAgKGV4aXQgYWxsKS4gT25lLWFuZC1kb25lICgxL2RheS9zeW1ib2wpLiBJZGVhbCBwZXJpb2RzCiAgICAgICAgMTA6MDAtMTM6MzAgRVQuIE9ubHkgdGFrZXMgUjpSID49IDEuMC4gVmFsaWRhdGVkIG9uIGEgMTRkIG5hdGl2ZS0xbWluIHJlcGxheSAodjM1MjoKICAgICAgICA2MyUgd2luLCB3aW5zb3JBdmcgKzAuNzBSLCBtZWRSICsxLjExUiwgYXZnIFI6UiA0LjggdG8gVldBUCkgXHUyMDE0IGRvY3RyaW5lLWZhaXRoZnVsIEFORAogICAgICAgIGZhciBiZXR0ZXIgdGhhbiB2MzQ4ICgrMC4yOFIpLiBDaGVhdC1zaGVldCBzdGF0czogNTAtNjAlIHdpbiwgfjEuNDoxIFI6Ui4KICAgICAgICAiIiIKICAgICAgICBSRUNFTlRfSyA9IDUKICAgICAgICBBQ0NFTCA9IDEuMwogICAgICAgIEhBTEZXQVkgPSAwLjUKICAgICAgICBNSU5fUlIgPSAxLjAKCiAgICAgICAgaWYgc2VsZi5fZ2V0X2N1cnJlbnRfdGltZV93aW5kb3coKSBub3QgaW4gKAogICAgICAgICAgICAgICAgVGltZVdpbmRvdy5NT1JOSU5HX1NFU1NJT04sIFRpbWVXaW5kb3cuTEFURV9NT1JOSU5HLCBUaW1lV2luZG93Lk1JRERBWSk6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgaWYgbm90IGdldGF0dHIoc25hcHNob3QsICJhYm92ZV9lbWE5IiwgRmFsc2UpOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIHRzID0gZ2V0YXR0cihzZWxmLCAidGVjaG5pY2FsX3NlcnZpY2UiLCBOb25lKQogICAgICAgIGlmIHRzIGlzIE5vbmU6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgYmFycyA9IHRzLl9nZXRfaW50cmFkYXlfYmFyc19mcm9tX2RiKHN5bWJvbCwgIjEgbWluIiwgNjApCiAgICAgICAgaWYgbm90IGJhcnMgb3IgbGVuKGJhcnMpIDwgUkVDRU5UX0sgKyAzOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIHZ3YXAgPSBmbG9hdChnZXRhdHRyKHNuYXBzaG90LCAidndhcCIsIDAuMCkgb3IgMC4wKQogICAgICAgIGVtYTkgPSBmbG9hdChnZXRhdHRyKHNuYXBzaG90LCAiZW1hXzkiLCAwLjApIG9yIDAuMCkKICAgICAgICBpZiB2d2FwIDw9IDAgb3IgZW1hOSA8PSAwOgogICAgICAgICAgICByZXR1cm4gTm9uZQoKICAgICAgICBjYXBzID0gZ2V0YXR0cihzZWxmLCAiX2JhY2tzaWRlX2RhaWx5X2NhcHMiLCBOb25lKQogICAgICAgIGlmIGNhcHMgaXMgTm9uZToKICAgICAgICAgICAgY2FwcyA9IHNlbGYuX2JhY2tzaWRlX2RhaWx5X2NhcHMgPSB7fQogICAgICAgIHRvZGF5ID0gZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0Yykuc3RyZnRpbWUoIiVZLSVtLSVkIikKICAgICAgICBrZXkgPSBmIntzeW1ib2x9Ont0b2RheX06bG9uZyIKICAgICAgICBpZiBjYXBzLmdldChrZXksIDApID49IDE6CiAgICAgICAgICAgIHJldHVybiBOb25lCgogICAgICAgIGRlZiBfbWVkaWFuKHhzKToKICAgICAgICAgICAgcyA9IHNvcnRlZCh4cykKICAgICAgICAgICAgbiA9IGxlbihzKQogICAgICAgICAgICBpZiBuID09IDA6CiAgICAgICAgICAgICAgICByZXR1cm4gMC4wCiAgICAgICAgICAgIHJldHVybiBzW24gLy8gMl0gaWYgbiAlIDIgZWxzZSAoc1tuIC8vIDIgLSAxXSArIHNbbiAvLyAyXSkgLyAyLjAKCiAgICAgICAgaSA9IGxlbihiYXJzKSAtIDEKICAgICAgICBpZiBpIDwgUkVDRU5UX0sgKyAxOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIGxhc3QgPSBiYXJzW2ldCiAgICAgICAgbG93cyA9IFtiWyJsb3ciXSBmb3IgYiBpbiBiYXJzIGlmIGIuZ2V0KCJsb3ciKSBpcyBub3QgTm9uZV0KICAgICAgICBpZiBub3QgbG93czoKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICBsb2QgPSBtaW4obG93cykKICAgICAgICByYW5nZXMgPSBbKGJbImhpZ2giXSAtIGJbImxvdyJdKSBmb3IgYiBpbiBiYXJzWzppXQogICAgICAgICAgICAgICAgICBpZiBiLmdldCgiaGlnaCIpIGlzIG5vdCBOb25lIGFuZCBiLmdldCgibG93IikgaXMgbm90IE5vbmVdCiAgICAgICAgbWVkX3IgPSBfbWVkaWFuKHJhbmdlcykKCiAgICAgICAgZ3JlZW4gPSBsYXN0WyJjbG9zZSJdID4gbGFzdFsib3BlbiJdCiAgICAgICAgY2xlYXJzX2hpID0gbGFzdFsiaGlnaCJdID4gbWF4KGJhcnNbaSAtIDFdWyJoaWdoIl0sIGJhcnNbaSAtIDJdWyJoaWdoIl0pCiAgICAgICAgZW50cnkgPSByb3VuZChtYXgoYmFyc1tpIC0gMV1bImhpZ2giXSwgYmFyc1tpIC0gMl1bImhpZ2giXSksIDIpCiAgICAgICAgcmVjZW50X2xvdyA9IG1pbihiYXJzW2pdWyJsb3ciXSBmb3IgaiBpbiByYW5nZShpIC0gUkVDRU5UX0ssIGkpKQogICAgICAgIGFjY2VsX29rID0gKG1lZF9yIDw9IDApIG9yICgobGFzdFsiaGlnaCJdIC0gbGFzdFsibG93Il0pID49IEFDQ0VMICogbWVkX3IpCiAgICAgICAgaWYgbm90IChncmVlbiBhbmQgY2xlYXJzX2hpIGFuZCBlbnRyeSA8IHZ3YXAgYW5kIGxhc3RbImNsb3NlIl0gPiBlbWE5CiAgICAgICAgICAgICAgICBhbmQgcmVjZW50X2xvdyA+IGxvZAogICAgICAgICAgICAgICAgYW5kIGVudHJ5ID4gbG9kICsgSEFMRldBWSAqICh2d2FwIC0gbG9kKQogICAgICAgICAgICAgICAgYW5kIGFjY2VsX29rKToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKCiAgICAgICAgc3RvcF9sb3NzID0gcm91bmQocmVjZW50X2xvdyAtIDAuMDIsIDIpCiAgICAgICAgcmlzayA9IGVudHJ5IC0gc3RvcF9sb3NzCiAgICAgICAgaWYgcmlzayA8PSAwIG9yIGVudHJ5IDw9IDA6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgdGFyZ2V0XzEgPSByb3VuZCh2d2FwLCAyKQogICAgICAgIHJyID0gKHRhcmdldF8xIC0gZW50cnkpIC8gcmlzawogICAgICAgIGlmIHJyIDwgTUlOX1JSOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIHJfbXVsdGlwbGUgPSByb3VuZChyciwgMikKICAgICAgICBwcmlvcml0eSA9IEFsZXJ0UHJpb3JpdHkuSElHSCBpZiB0YXBlLmNvbmZpcm1hdGlvbl9mb3JfbG9uZyBlbHNlIEFsZXJ0UHJpb3JpdHkuTUVESVVNCiAgICAgICAgZXZfaW5mbyA9ICIiCiAgICAgICAgaWYgImJhY2tzaWRlIiBpbiBzZWxmLl9zdHJhdGVneV9zdGF0czoKICAgICAgICAgICAgc3QgPSBzZWxmLl9zdHJhdGVneV9zdGF0c1siYmFja3NpZGUiXQogICAgICAgICAgICBpZiBzdC53aW5fcmF0ZSA+IDA6CiAgICAgICAgICAgICAgICBldl9pbmZvID0gZiJIaXN0b3JpY2FsOiB7c3Qud2luX3JhdGU6LjAlfSB3aW4sIEVWIHtzdC5leHBlY3RlZF92YWx1ZV9yOi4yZn1SIgogICAgICAgIGNhcHNba2V5XSA9IGNhcHMuZ2V0KGtleSwgMCkgKyAxCiAgICAgICAgaGxfZGlzdCA9ICh2d2FwIC0gZW50cnkpIC8gdndhcCAqIDEwMC4wCiAgICAgICAgdGFwZV90YWcgPSAiXHUyNzEzIFRBUEUiIGlmIHRhcGUuY29uZmlybWF0aW9uX2Zvcl9sb25nIGVsc2UgIiIKICAgICAgICByZXR1cm4gTGl2ZUFsZXJ0KAogICAgICAgICAgICBpZD1mImJhY2tzaWRlX3tzeW1ib2x9X3tkYXRldGltZS5ub3coKS5zdHJmdGltZSgnJUglTSVTJyl9IiwKICAgICAgICAgICAgc3ltYm9sPXN5bWJvbCwKICAgICAgICAgICAgc2V0dXBfdHlwZT0iYmFja3NpZGUiLAogICAgICAgICAgICBzdHJhdGVneV9uYW1lPSJCYWNrJGlkZSBTY2FscCAoSU5ULTMyKSIsCiAgICAgICAgICAgIGRpcmVjdGlvbj0ibG9uZyIsCiAgICAgICAgICAgIHByaW9yaXR5PXByaW9yaXR5LAogICAgICAgICAgICBjdXJyZW50X3ByaWNlPXNuYXBzaG90LmN1cnJlbnRfcHJpY2UsCiAgICAgICAgICAgIHRyaWdnZXJfcHJpY2U9ZW50cnksCiAgICAgICAgICAgIHN0b3BfbG9zcz1zdG9wX2xvc3MsCiAgICAgICAgICAgIHRhcmdldD10YXJnZXRfMSwKICAgICAgICAgICAgcmlza19yZXdhcmQ9cl9tdWx0aXBsZSwKICAgICAgICAgICAgdHJpZ2dlcl9wcm9iYWJpbGl0eT0wLjYzLAogICAgICAgICAgICB3aW5fcHJvYmFiaWxpdHk9MC42MywKICAgICAgICAgICAgbWludXRlc190b190cmlnZ2VyPTAsCiAgICAgICAgICAgIGhlYWRsaW5lPWYiXFUwMDAxZjNhZiB7c3ltYm9sfSBCYWNrJGlkZSBcdTIwMTQgaGlnaGVyLWxvdyByZWNsYWltIHRvIFZXQVAgKFI6UiB7cl9tdWx0aXBsZTouMWZ9KSB7dGFwZV90YWd9IiwKICAgICAgICAgICAgcmVhc29uaW5nPVsKICAgICAgICAgICAgICAgIGYiUmlzaW5nIGJhY2skaWRlOiBoaWdoZXItbG93ICR7cmVjZW50X2xvdzouMmZ9ID4gTE9EICR7bG9kOi4yZn0sIGdyZWVuIGJhciBicm9rZSBwcmlvci0yIGhpZ2hzIiwKICAgICAgICAgICAgICAgIGYiUmVjb3ZlcmVkIHtobF9kaXN0Oi4xZn0lIGJlbG93IFZXQVAgJHt2d2FwOi4yZn0gKD5oYWxmd2F5IGZyb20gTE9EKSwgaG9sZGluZyBhYm92ZSA5LUVNQSIsCiAgICAgICAgICAgICAgICBmIlI6UiA9IHtyX211bHRpcGxlOi4xZn06MSAoVElHSFQgc3RvcCAke3N0b3BfbG9zczouMmZ9ID0gLjAyIGJlbG93IGhpZ2hlciBsb3csIFRhcmdldCBWV0FQICR7dGFyZ2V0XzE6LjJmfSkiLAogICAgICAgICAgICAgICAgZiJUYXBlOiB7dGFwZS5vdmVyYWxsX3NpZ25hbC52YWx1ZX0iLAogICAgICAgICAgICAgICAgZXZfaW5mbyBpZiBldl9pbmZvIGVsc2UgIkNoZWF0LXNoZWV0IGJhY2skaWRlICh2MzUyIHJlcGxheSA2MyUgd2luLCArMC43MFIsIGF2ZyBSOlIgNC44IHRvIFZXQVApIiwKICAgICAgICAgICAgICAgICJPbmUtYW5kLWRvbmUgc2NhbHAsIDEwOjAwLTEzOjMwIEVUIHdpbmRvdyAoU01CIEJhY2skaWRlIGRvY3RyaW5lKSIsCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgIHRpbWVfd2luZG93PXNlbGYuX2dldF9jdXJyZW50X3RpbWVfd2luZG93KCkudmFsdWUsCiAgICAgICAgICAgIG1hcmtldF9yZWdpbWU9c2VsZi5fbWFya2V0X3JlZ2ltZS52YWx1ZSwKICAgICAgICAgICAgZXhwaXJlc19hdD0oZGF0ZXRpbWUubm93KHRpbWV6b25lLnV0YykgKyB0aW1lZGVsdGEoaG91cnM9MSkpLmlzb2Zvcm1hdCgpCiAgICAgICAgKQogICAgICAgIHJldHVybiBOb25lCiAgICAK"
BACKUP = FILE + ".bak_v352"


def _sha(s): return hashlib.sha256(s.encode("utf-8")).hexdigest()
def _read():
    if not os.path.exists(FILE):
        print(f"ERROR: {FILE} not found (run from repo root)"); sys.exit(2)
    return open(FILE, encoding="utf-8").read()
def _old(): return base64.b64decode(OLD_B64).decode("utf-8")
def _new(): return base64.b64decode(NEW_B64).decode("utf-8")
def _compiles(text):
    with tempfile.NamedTemporaryFile("w", suffix=".py", delete=False) as tf:
        tf.write(text); tmp = tf.name
    try:
        py_compile.compile(tmp, doraise=True); return True
    except py_compile.PyCompileError as e:
        print("POST-PATCH COMPILE FAILED:\n", e); return False
    finally:
        os.unlink(tmp)


def check():
    src = _read(); cur = _sha(src); old = _old()
    print(f"file            : {FILE}")
    print(f"whole-file SHA  : {cur}")
    print(f"expected (DGX)  : {DGX_WHOLE_PRE}  {'OK' if cur == DGX_WHOLE_PRE else 'DRIFT!'}")
    print(f"func anchor     : present={old in src} count={src.count(old)}")
    print(f"func PRE sha    : {_sha(old)}  {'OK' if _sha(old) == PRE_FUNC_SHA else 'MISMATCH'}")
    print(f"func POST sha   : {_sha(_new())}  {'OK' if _sha(_new()) == POST_FUNC_SHA else 'MISMATCH'}")
    if _new() in src: print("state           : ALREADY PATCHED")
    if cur != DGX_WHOLE_PRE:
        print("\nDRIFT: live file != DGX baseline. Re-extract and rebuild."); return False
    if src.count(old) != 1:
        print("\nAnchor missing/ambiguous -- abort."); return False
    print("\nREADY: --apply installs the cheat-sheet Back$ide (tight higher-low stop -> VWAP).")
    return True


def apply():
    src = _read(); old, new = _old(), _new()
    if new in src: print("Already patched. No-op."); return
    if _sha(src) != DGX_WHOLE_PRE:
        print(f"ABORT: whole-file SHA {_sha(src)} != DGX baseline. See --check."); sys.exit(3)
    if src.count(old) != 1:
        print(f"ABORT: anchor count={src.count(old)} (need 1)."); sys.exit(3)
    if _sha(old) != PRE_FUNC_SHA:
        print("ABORT: function PRE sha mismatch."); sys.exit(3)
    if _sha(new) != POST_FUNC_SHA:
        print("ABORT: embedded NEW function sha mismatch (corrupt patcher)."); sys.exit(3)
    patched = src.replace(old, new, 1)
    if not _compiles(patched):
        print("ABORT: patched file does not compile. No write."); sys.exit(3)
    shutil.copy2(FILE, BACKUP)
    with open(FILE, "w", encoding="utf-8") as f: f.write(patched)
    print(f"APPLIED. backup -> {BACKUP}")
    print(f"new whole-file SHA : {_sha(patched)}  (record this)")
    print("Verify: pytest backend/tests/test_v352_backside.py -q ; commit BEFORE restart ; ./start_backend.sh --force")


def rollback():
    src = _read(); old, new = _old(), _new()
    if old in src and _sha(src) == DGX_WHOLE_PRE:
        print("Already at baseline (v348). No-op."); return
    if new in src and src.count(new) == 1:
        restored = src.replace(new, old, 1)
        shutil.copy2(FILE, FILE + ".bak_pre_rollback")
        with open(FILE, "w", encoding="utf-8") as f: f.write(restored)
        print(f"ROLLED BACK via reverse-anchor. whole-file SHA == DGX baseline: {_sha(restored) == DGX_WHOLE_PRE}")
        return
    if os.path.exists(BACKUP):
        bsrc = open(BACKUP, encoding="utf-8").read()
        if _sha(bsrc) == DGX_WHOLE_PRE:
            shutil.copy2(BACKUP, FILE); print(f"ROLLED BACK from {BACKUP} (== DGX baseline)."); return
    print("ABORT: could not safely roll back."); sys.exit(4)


if __name__ == "__main__":
    arg = sys.argv[1] if len(sys.argv) > 1 else "--check"
    {"--check": check, "--apply": apply, "--rollback": rollback}.get(arg, lambda: print("usage: --check | --apply | --rollback"))()
