#!/usr/bin/env python3
# patch_v358_daily_squeeze_long_only.py
# ---------------------------------------------------------------------------
# v358 — gate `_check_daily_squeeze` to LONG-ONLY (suppress the momentum-short branch).
#
# EVIDENCE (diag_v358_daily_squeeze_replay.py, 365d / 400-sym daily IB bars):
#   The setup is a LONG-only edge — SHORT loses in EVERY config tested:
#     | config                 | LONG winsorAvg / totW | SHORT winsorAvg / totW |
#     | compression/±10% (LIVE)| +0.073 / +1532.7      | -0.056 / -1067.1       |
#     | release/±10%           | +0.053 / +396.5       | -0.071 / -452.7        |
#     | compression/2.5ATR     | +0.061 / +1287.5      | -0.041 / -789.9        |
#     | release/2.5ATR         | +0.047 / +348.1       | -0.072 / -455.7        |
#     | tight0.5 / hold20      | +0.083 / +889.5       | -0.088 / -846.2        |
#   The momentum-short branch (shorting a daily squeeze in a drift-up tape) drags a solidly
#   +EV long side to breakeven. Fix = keep the long edge, suppress shorts. Geometry unchanged
#   (compression + ±10% target is already the best long config).
#
# Anchored-chunk patcher (AGENTS.md §2): whole-file PRE-SHA guard + exact OLD-bytes match
# (count MUST be 1) + post-write self-verify. ABORTS before writing on ANY drift. Backs up
# the original. Supports --check dry-run. Only inserts a `if direction != "long": return None`
# gate right after the direction is computed; nothing else changes.
#
# Deploy (DGX, repo root):
#   curl -sS -o /tmp/patch_v358.py https://paste.rs/<id>
#   .venv/bin/python /tmp/patch_v358.py --check
#   .venv/bin/python /tmp/patch_v358.py
#   .venv/bin/python -m pytest backend/tests/test_v358_daily_squeeze_long_only.py -q
#   git add backend/ memory/ && git commit -m "v358: daily_squeeze long-only (short branch is -EV)" && git push origin main
#   ./start_backend.sh --force
# ---------------------------------------------------------------------------
import base64
import hashlib
import shutil
import sys

FILE = "backend/services/enhanced_scanner.py"

PRE_FILE_SHA = "36067838a2bf786444b825b81d0e328626be8fcbad74ba712fd33ae792d9c182"

OLD_B64 = "ICAgIGFzeW5jIGRlZiBfY2hlY2tfZGFpbHlfc3F1ZWV6ZShzZWxmLCBzeW1ib2w6IHN0ciwgYmFyczogbGlzdCkgLT4gT3B0aW9uYWxbTGl2ZUFsZXJ0XToKICAgICAgICAiIiJCb2xsaW5nZXIgQmFuZHMgaW5zaWRlIEtlbHRuZXIgQ2hhbm5lbHMgb24gREFJTFkgYmFycyA9IG11bHRpLWRheSBzcXVlZXplLiIiIgogICAgICAgIGlmIGxlbihiYXJzKSA8IDIwOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIAogICAgICAgIGNsb3NlcyA9IFtiWyJjbG9zZSJdIGZvciBiIGluIGJhcnNdCiAgICAgICAgaGlnaHMgPSBbYlsiaGlnaCJdIGZvciBiIGluIGJhcnNdCiAgICAgICAgbG93cyA9IFtiWyJsb3ciXSBmb3IgYiBpbiBiYXJzXQogICAgICAgIAogICAgICAgICMgMjAtcGVyaW9kIFNNQSBhbmQgQm9sbGluZ2VyIEJhbmRzCiAgICAgICAgc21hMjAgPSBzdW0oY2xvc2VzWy0yMDpdKSAvIDIwCiAgICAgICAgc3RkMjAgPSAoc3VtKChjIC0gc21hMjApICoqIDIgZm9yIGMgaW4gY2xvc2VzWy0yMDpdKSAvIDIwKSAqKiAwLjUKICAgICAgICBiYl91cHBlciA9IHNtYTIwICsgMiAqIHN0ZDIwCiAgICAgICAgYmJfbG93ZXIgPSBzbWEyMCAtIDIgKiBzdGQyMAogICAgICAgIGJiX3dpZHRoID0gKGJiX3VwcGVyIC0gYmJfbG93ZXIpIC8gc21hMjAgKiAxMDAgaWYgc21hMjAgPiAwIGVsc2UgOTk5CiAgICAgICAgCiAgICAgICAgIyBLZWx0bmVyIENoYW5uZWxzICgyMC1wZXJpb2QgRU1BICsgMS41ICogQVRSKQogICAgICAgIGF0cnMgPSBbXQogICAgICAgIGZvciBpIGluIHJhbmdlKDEsIG1pbigxNSwgbGVuKGJhcnMpKSk6CiAgICAgICAgICAgIHRyID0gbWF4KAogICAgICAgICAgICAgICAgaGlnaHNbLShpKV0gLSBsb3dzWy0oaSldLAogICAgICAgICAgICAgICAgYWJzKGhpZ2hzWy0oaSldIC0gY2xvc2VzWy0oaSsxKV0pLAogICAgICAgICAgICAgICAgYWJzKGxvd3NbLShpKV0gLSBjbG9zZXNbLShpKzEpXSkKICAgICAgICAgICAgKQogICAgICAgICAgICBhdHJzLmFwcGVuZCh0cikKICAgICAgICBhdHIgPSBzdW0oYXRycykgLyBsZW4oYXRycykgaWYgYXRycyBlbHNlIDAKICAgICAgICBrY191cHBlciA9IHNtYTIwICsgMS41ICogYXRyCiAgICAgICAga2NfbG93ZXIgPSBzbWEyMCAtIDEuNSAqIGF0cgogICAgICAgIAogICAgICAgICMgU3F1ZWV6ZTogQkIgaW5zaWRlIEtDCiAgICAgICAgaXNfc3F1ZWV6ZSA9IGJiX3VwcGVyIDwga2NfdXBwZXIgYW5kIGJiX2xvd2VyID4ga2NfbG93ZXIKICAgICAgICBpZiBub3QgaXNfc3F1ZWV6ZToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICAKICAgICAgICAjIEFkYXB0aXZlIEJCIHdpZHRoIHRocmVzaG9sZDogY29tcGFyZSB0byBzdG9jaydzIG93biBoaXN0b3JpY2FsIEJCIHdpZHRoCiAgICAgICAgIyBDYWxjdWxhdGUgbWVkaWFuIEJCIHdpZHRoIG92ZXIgbGFzdCA0MCBiYXJzCiAgICAgICAgaGlzdF93aWR0aHMgPSBbXQogICAgICAgIGZvciBpIGluIHJhbmdlKDIwLCBtaW4oNDAsIGxlbihjbG9zZXMpKSk6CiAgICAgICAgICAgIHMgPSBzdW0oY2xvc2VzW2ktMjA6aV0pIC8gMjAKICAgICAgICAgICAgc2QgPSAoc3VtKChjIC0gcykgKiogMiBmb3IgYyBpbiBjbG9zZXNbaS0yMDppXSkgLyAyMCkgKiogMC41CiAgICAgICAgICAgIHcgPSAoNCAqIHNkKSAvIHMgKiAxMDAgaWYgcyA+IDAgZWxzZSAwCiAgICAgICAgICAgIGhpc3Rfd2lkdGhzLmFwcGVuZCh3KQogICAgICAgIAogICAgICAgIGlmIGhpc3Rfd2lkdGhzOgogICAgICAgICAgICBtZWRpYW5fd2lkdGggPSBzb3J0ZWQoaGlzdF93aWR0aHMpW2xlbihoaXN0X3dpZHRocykgLy8gMl0KICAgICAgICAgICAgIyBTcXVlZXplIGlzIHNpZ25pZmljYW50IGlmIGN1cnJlbnQgd2lkdGggaXMgPCA3MCUgb2YgaGlzdG9yaWNhbCBtZWRpYW4KICAgICAgICAgICAgaWYgYmJfd2lkdGggPiBtZWRpYW5fd2lkdGggKiAwLjc6CiAgICAgICAgICAgICAgICByZXR1cm4gTm9uZSAgIyBOb3QgdGlnaHQgZW5vdWdoIHJlbGF0aXZlIHRvIHRoaXMgc3RvY2sncyBub3JtCiAgICAgICAgZWxzZToKICAgICAgICAgICAgIyBGYWxsYmFjazogYWJzb2x1dGUgdGhyZXNob2xkCiAgICAgICAgICAgIGlmIGJiX3dpZHRoID4gMTU6CiAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIAogICAgICAgICMgRGV0ZXJtaW5lIGRpcmVjdGlvbiBmcm9tIG1vbWVudHVtIChjbG9zZSB2cyBTTUEpCiAgICAgICAgbW9tZW50dW0gPSBjbG9zZXNbLTFdIC0gc21hMjAKICAgICAgICBkaXJlY3Rpb24gPSAibG9uZyIgaWYgbW9tZW50dW0gPiAwIGVsc2UgInNob3J0IgogICAgICAgIAogICAgICAgIGN1cnJlbnQgPSBjbG9zZXNbLTFdCiAgICAgICAgIyB2MTkuMzQuNTQ6IEFUUi1mbG9vcmVkIHN0b3AgdXNpbmcgdGhlIHNxdWVlemUtcGVyaW9kIHN0cnVjdHVyYWwKICAgICAgICAjIGFuY2hvciAobG93ZXN0IGxvdyAvIGhpZ2hlc3QgaGlnaCBvZiB0aGUgMjAtYmFyIEJCIHdpbmRvdykuCiAgICAgICAgIyBtaW5fYXRyX211bHQ9MS41IG1hdGNoZXMgdGhlIEtlbHRuZXIgY2hhbm5lbCB3aWR0aCBhbmQgcHJvdmlkZXMKICAgICAgICAjIGFwcHJvcHJpYXRlIG92ZXJuaWdodCBnYXAgaGVhZHJvb20gZm9yIGEgZGFpbHktdGltZWZyYW1lIHN3aW5nLgogICAgICAgICMgUmVwbGFjZXMgdGhlIHByaW9yIGhhcmRjb2RlZCA1JSBzdG9wIHRoYXQgaWdub3JlZCBBVFIgZW50aXJlbHkKICAgICAgICAjIGFuZCB3YXMgdGhlIG9ubHkgcmVtYWluaW5nIG5vbi10cmFkaW5nIHNjYW5uZXIgc2V0dXAgbm90IHVzaW5nCiAgICAgICAgIyBfYXRyX2Zsb29yZWRfc3RvcCBhZnRlciB2MTkuMzQuNTAuCiAgICAgICAgaWYgZGlyZWN0aW9uID09ICJsb25nIjoKICAgICAgICAgICAgc3RydWN0dXJhbF9hbmNob3IgPSBtaW4obG93c1stMjA6XSkgLSAwLjAyCiAgICAgICAgZWxzZToKICAgICAgICAgICAgc3RydWN0dXJhbF9hbmNob3IgPSBtYXgoaGlnaHNbLTIwOl0pICsgMC4wMgogICAgICAgIHN0b3AgPSBzZWxmLl9hdHJfZmxvb3JlZF9zdG9wKAogICAgICAgICAgICBlbnRyeV9wcmljZT1jdXJyZW50LAogICAgICAgICAgICByYXdfc3RvcD1zdHJ1Y3R1cmFsX2FuY2hvciwKICAgICAgICAgICAgYXRyPWF0ciwKICAgICAgICAgICAgZGlyZWN0aW9uPWRpcmVjdGlvbiwKICAgICAgICAgICAgbWluX2F0cl9tdWx0PTEuNSwKICAgICAgICApCiAgICAgICAgdGFyZ2V0ID0gY3VycmVudCAqICgxLjEwIGlmIGRpcmVjdGlvbiA9PSAibG9uZyIgZWxzZSAwLjkwKQogICAgICAgIAogICAgICAgIHJldHVybiBMaXZlQWxlcnQoCiAgICAgICAgICAgIGlkPWYiZGFpbHlfc3F1ZWV6ZV97c3ltYm9sfV97ZGlyZWN0aW9ufV97ZGF0ZXRpbWUubm93KCkuc3RyZnRpbWUoJyVIJU0lUycpfSIsCiAgICAgICAgICAgIHN5bWJvbD1zeW1ib2wsCiAgICAgICAgICAgIHNldHVwX3R5cGU9ImRhaWx5X3NxdWVlemUiLAogICAgICAgICAgICBzdHJhdGVneV9uYW1lPSJkYWlseV9zcXVlZXplIiwKICAgICAgICAgICAgZGlyZWN0aW9uPWRpcmVjdGlvbiwKICAgICAgICAgICAgcHJpb3JpdHk9QWxlcnRQcmlvcml0eS5ISUdILAogICAgICAgICAgICBjdXJyZW50X3ByaWNlPWN1cnJlbnQsCiAgICAgICAgICAgIHRyaWdnZXJfcHJpY2U9Y3VycmVudCwKICAgICAgICAgICAgc3RvcF9sb3NzPXJvdW5kKHN0b3AsIDIpLAogICAgICAgICAgICB0YXJnZXQ9cm91bmQodGFyZ2V0LCAyKSwKICAgICAgICAgICAgcmlza19yZXdhcmQ9YWJzKHRhcmdldCAtIGN1cnJlbnQpIC8gYWJzKGN1cnJlbnQgLSBzdG9wKSBpZiBhYnMoY3VycmVudCAtIHN0b3ApID4gMCBlbHNlIDAsCiAgICAgICAgICAgIHRyaWdnZXJfcHJvYmFiaWxpdHk9MC42LAogICAgICAgICAgICB3aW5fcHJvYmFiaWxpdHk9MC41NSwKICAgICAgICAgICAgbWludXRlc190b190cmlnZ2VyPTAsCiAgICAgICAgICAgIGhlYWRsaW5lPWYie3N5bWJvbH0gREFJTFkgU1FVRUVaRSAoe2RpcmVjdGlvbi51cHBlcigpfSkgLSBCQiBXaWR0aCB7YmJfd2lkdGg6LjFmfSUiLAogICAgICAgICAgICByZWFzb25pbmc9WwogICAgICAgICAgICAgICAgIkRhaWx5IEJvbGxpbmdlciBCYW5kcyBJTlNJREUgS2VsdG5lciBDaGFubmVscyA9IG11bHRpLWRheSB2b2xhdGlsaXR5IHNxdWVlemUiLAogICAgICAgICAgICAgICAgZiJCQiBXaWR0aDoge2JiX3dpZHRoOi4xZn0lICh0aWdodCA9IGV4cGxvc2l2ZSBicmVha291dCBpbW1pbmVudCkiLAogICAgICAgICAgICAgICAgZiJNb21lbnR1bTogeydidWxsaXNoJyBpZiBtb21lbnR1bSA+IDAgZWxzZSAnYmVhcmlzaCd9IChjbG9zZSB7J2Fib3ZlJyBpZiBtb21lbnR1bSA+IDAgZWxzZSAnYmVsb3cnfSAyMCBTTUEpIiwKICAgICAgICAgICAgICAgIGYiQVRSOiAke2F0cjouMmZ9IHwgU3dpbmcgdHJhZGUgLSBob2xkIG92ZXJuaWdodCIsCiAgICAgICAgICAgIF0sCiAgICAgICAgICAgIHRpbWVfd2luZG93PSJEQUlMWSIsCiAgICAgICAgICAgIG1hcmtldF9yZWdpbWU9Im5ldXRyYWwiLAogICAgICAgICAgICB0cmFkZV9zdHlsZT0ibXVsdGlfZGF5IiwKICAgICAgICAgICAgc2V0dXBfY2F0ZWdvcnk9ImNvbnNvbGlkYXRpb24iLAogICAgICAgICAgICBzY2FuX3RpZXI9InN3aW5nIiwKICAgICAgICAgICAgZGlyZWN0aW9uX2JpYXM9ZGlyZWN0aW9uLAogICAgICAgICAgICBleHBpcmVzX2F0PShkYXRldGltZS5ub3codGltZXpvbmUudXRjKSArIHRpbWVkZWx0YShob3Vycz0yNCkpLmlzb2Zvcm1hdCgpCiAgICAgICAgKQoK"

NEW_B64 = "ICAgIGFzeW5jIGRlZiBfY2hlY2tfZGFpbHlfc3F1ZWV6ZShzZWxmLCBzeW1ib2w6IHN0ciwgYmFyczogbGlzdCkgLT4gT3B0aW9uYWxbTGl2ZUFsZXJ0XToKICAgICAgICAiIiJCb2xsaW5nZXIgQmFuZHMgaW5zaWRlIEtlbHRuZXIgQ2hhbm5lbHMgb24gREFJTFkgYmFycyA9IG11bHRpLWRheSBzcXVlZXplLiIiIgogICAgICAgIGlmIGxlbihiYXJzKSA8IDIwOgogICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIAogICAgICAgIGNsb3NlcyA9IFtiWyJjbG9zZSJdIGZvciBiIGluIGJhcnNdCiAgICAgICAgaGlnaHMgPSBbYlsiaGlnaCJdIGZvciBiIGluIGJhcnNdCiAgICAgICAgbG93cyA9IFtiWyJsb3ciXSBmb3IgYiBpbiBiYXJzXQogICAgICAgIAogICAgICAgICMgMjAtcGVyaW9kIFNNQSBhbmQgQm9sbGluZ2VyIEJhbmRzCiAgICAgICAgc21hMjAgPSBzdW0oY2xvc2VzWy0yMDpdKSAvIDIwCiAgICAgICAgc3RkMjAgPSAoc3VtKChjIC0gc21hMjApICoqIDIgZm9yIGMgaW4gY2xvc2VzWy0yMDpdKSAvIDIwKSAqKiAwLjUKICAgICAgICBiYl91cHBlciA9IHNtYTIwICsgMiAqIHN0ZDIwCiAgICAgICAgYmJfbG93ZXIgPSBzbWEyMCAtIDIgKiBzdGQyMAogICAgICAgIGJiX3dpZHRoID0gKGJiX3VwcGVyIC0gYmJfbG93ZXIpIC8gc21hMjAgKiAxMDAgaWYgc21hMjAgPiAwIGVsc2UgOTk5CiAgICAgICAgCiAgICAgICAgIyBLZWx0bmVyIENoYW5uZWxzICgyMC1wZXJpb2QgRU1BICsgMS41ICogQVRSKQogICAgICAgIGF0cnMgPSBbXQogICAgICAgIGZvciBpIGluIHJhbmdlKDEsIG1pbigxNSwgbGVuKGJhcnMpKSk6CiAgICAgICAgICAgIHRyID0gbWF4KAogICAgICAgICAgICAgICAgaGlnaHNbLShpKV0gLSBsb3dzWy0oaSldLAogICAgICAgICAgICAgICAgYWJzKGhpZ2hzWy0oaSldIC0gY2xvc2VzWy0oaSsxKV0pLAogICAgICAgICAgICAgICAgYWJzKGxvd3NbLShpKV0gLSBjbG9zZXNbLShpKzEpXSkKICAgICAgICAgICAgKQogICAgICAgICAgICBhdHJzLmFwcGVuZCh0cikKICAgICAgICBhdHIgPSBzdW0oYXRycykgLyBsZW4oYXRycykgaWYgYXRycyBlbHNlIDAKICAgICAgICBrY191cHBlciA9IHNtYTIwICsgMS41ICogYXRyCiAgICAgICAga2NfbG93ZXIgPSBzbWEyMCAtIDEuNSAqIGF0cgogICAgICAgIAogICAgICAgICMgU3F1ZWV6ZTogQkIgaW5zaWRlIEtDCiAgICAgICAgaXNfc3F1ZWV6ZSA9IGJiX3VwcGVyIDwga2NfdXBwZXIgYW5kIGJiX2xvd2VyID4ga2NfbG93ZXIKICAgICAgICBpZiBub3QgaXNfc3F1ZWV6ZToKICAgICAgICAgICAgcmV0dXJuIE5vbmUKICAgICAgICAKICAgICAgICAjIEFkYXB0aXZlIEJCIHdpZHRoIHRocmVzaG9sZDogY29tcGFyZSB0byBzdG9jaydzIG93biBoaXN0b3JpY2FsIEJCIHdpZHRoCiAgICAgICAgIyBDYWxjdWxhdGUgbWVkaWFuIEJCIHdpZHRoIG92ZXIgbGFzdCA0MCBiYXJzCiAgICAgICAgaGlzdF93aWR0aHMgPSBbXQogICAgICAgIGZvciBpIGluIHJhbmdlKDIwLCBtaW4oNDAsIGxlbihjbG9zZXMpKSk6CiAgICAgICAgICAgIHMgPSBzdW0oY2xvc2VzW2ktMjA6aV0pIC8gMjAKICAgICAgICAgICAgc2QgPSAoc3VtKChjIC0gcykgKiogMiBmb3IgYyBpbiBjbG9zZXNbaS0yMDppXSkgLyAyMCkgKiogMC41CiAgICAgICAgICAgIHcgPSAoNCAqIHNkKSAvIHMgKiAxMDAgaWYgcyA+IDAgZWxzZSAwCiAgICAgICAgICAgIGhpc3Rfd2lkdGhzLmFwcGVuZCh3KQogICAgICAgIAogICAgICAgIGlmIGhpc3Rfd2lkdGhzOgogICAgICAgICAgICBtZWRpYW5fd2lkdGggPSBzb3J0ZWQoaGlzdF93aWR0aHMpW2xlbihoaXN0X3dpZHRocykgLy8gMl0KICAgICAgICAgICAgIyBTcXVlZXplIGlzIHNpZ25pZmljYW50IGlmIGN1cnJlbnQgd2lkdGggaXMgPCA3MCUgb2YgaGlzdG9yaWNhbCBtZWRpYW4KICAgICAgICAgICAgaWYgYmJfd2lkdGggPiBtZWRpYW5fd2lkdGggKiAwLjc6CiAgICAgICAgICAgICAgICByZXR1cm4gTm9uZSAgIyBOb3QgdGlnaHQgZW5vdWdoIHJlbGF0aXZlIHRvIHRoaXMgc3RvY2sncyBub3JtCiAgICAgICAgZWxzZToKICAgICAgICAgICAgIyBGYWxsYmFjazogYWJzb2x1dGUgdGhyZXNob2xkCiAgICAgICAgICAgIGlmIGJiX3dpZHRoID4gMTU6CiAgICAgICAgICAgICAgICByZXR1cm4gTm9uZQogICAgICAgIAogICAgICAgICMgRGV0ZXJtaW5lIGRpcmVjdGlvbiBmcm9tIG1vbWVudHVtIChjbG9zZSB2cyBTTUEpCiAgICAgICAgbW9tZW50dW0gPSBjbG9zZXNbLTFdIC0gc21hMjAKICAgICAgICBkaXJlY3Rpb24gPSAibG9uZyIgaWYgbW9tZW50dW0gPiAwIGVsc2UgInNob3J0IgogICAgICAgICMgdjM1OCDigJQgTE9ORy1PTkxZIGdhdGUuIFJlcGxheSAoMzY1ZCAvIDQwMC1zeW0gZGFpbHkpIHByb3ZlZCB0aGUgbW9tZW50dW0tU0hPUlQKICAgICAgICAjIGJyYW5jaCBpcyBuZWdhdGl2ZS1FViBpbiBFVkVSWSBjb25maWcgKHdpbnNvckF2ZyAtMC4wNC4uLTAuMDksIHRvdFcgLTAuOGsuLi0xLjFrKSwKICAgICAgICAjIGRyYWdnaW5nIGEgc29saWRseSArRVYgbG9uZyBzaWRlICgrMC4wNzMgUi90cmFkZSwgNTElIHdpbikgdG8gYnJlYWtldmVuLiBTdXBwcmVzcwogICAgICAgICMgc2hvcnRzOyBrZWVwIHRoZSBsb25nIGVkZ2UuIFNlZSBtZW1vcnkvdjM1OF9kYWlseV9zcXVlZXplX2J1aWxkLm1kLgogICAgICAgIGlmIGRpcmVjdGlvbiAhPSAibG9uZyI6CiAgICAgICAgICAgIHJldHVybiBOb25lCiAgICAgICAgCiAgICAgICAgY3VycmVudCA9IGNsb3Nlc1stMV0KICAgICAgICAjIHYxOS4zNC41NDogQVRSLWZsb29yZWQgc3RvcCB1c2luZyB0aGUgc3F1ZWV6ZS1wZXJpb2Qgc3RydWN0dXJhbAogICAgICAgICMgYW5jaG9yIChsb3dlc3QgbG93IC8gaGlnaGVzdCBoaWdoIG9mIHRoZSAyMC1iYXIgQkIgd2luZG93KS4KICAgICAgICAjIG1pbl9hdHJfbXVsdD0xLjUgbWF0Y2hlcyB0aGUgS2VsdG5lciBjaGFubmVsIHdpZHRoIGFuZCBwcm92aWRlcwogICAgICAgICMgYXBwcm9wcmlhdGUgb3Zlcm5pZ2h0IGdhcCBoZWFkcm9vbSBmb3IgYSBkYWlseS10aW1lZnJhbWUgc3dpbmcuCiAgICAgICAgIyBSZXBsYWNlcyB0aGUgcHJpb3IgaGFyZGNvZGVkIDUlIHN0b3AgdGhhdCBpZ25vcmVkIEFUUiBlbnRpcmVseQogICAgICAgICMgYW5kIHdhcyB0aGUgb25seSByZW1haW5pbmcgbm9uLXRyYWRpbmcgc2Nhbm5lciBzZXR1cCBub3QgdXNpbmcKICAgICAgICAjIF9hdHJfZmxvb3JlZF9zdG9wIGFmdGVyIHYxOS4zNC41MC4KICAgICAgICBpZiBkaXJlY3Rpb24gPT0gImxvbmciOgogICAgICAgICAgICBzdHJ1Y3R1cmFsX2FuY2hvciA9IG1pbihsb3dzWy0yMDpdKSAtIDAuMDIKICAgICAgICBlbHNlOgogICAgICAgICAgICBzdHJ1Y3R1cmFsX2FuY2hvciA9IG1heChoaWdoc1stMjA6XSkgKyAwLjAyCiAgICAgICAgc3RvcCA9IHNlbGYuX2F0cl9mbG9vcmVkX3N0b3AoCiAgICAgICAgICAgIGVudHJ5X3ByaWNlPWN1cnJlbnQsCiAgICAgICAgICAgIHJhd19zdG9wPXN0cnVjdHVyYWxfYW5jaG9yLAogICAgICAgICAgICBhdHI9YXRyLAogICAgICAgICAgICBkaXJlY3Rpb249ZGlyZWN0aW9uLAogICAgICAgICAgICBtaW5fYXRyX211bHQ9MS41LAogICAgICAgICkKICAgICAgICB0YXJnZXQgPSBjdXJyZW50ICogKDEuMTAgaWYgZGlyZWN0aW9uID09ICJsb25nIiBlbHNlIDAuOTApCiAgICAgICAgCiAgICAgICAgcmV0dXJuIExpdmVBbGVydCgKICAgICAgICAgICAgaWQ9ZiJkYWlseV9zcXVlZXplX3tzeW1ib2x9X3tkaXJlY3Rpb259X3tkYXRldGltZS5ub3coKS5zdHJmdGltZSgnJUglTSVTJyl9IiwKICAgICAgICAgICAgc3ltYm9sPXN5bWJvbCwKICAgICAgICAgICAgc2V0dXBfdHlwZT0iZGFpbHlfc3F1ZWV6ZSIsCiAgICAgICAgICAgIHN0cmF0ZWd5X25hbWU9ImRhaWx5X3NxdWVlemUiLAogICAgICAgICAgICBkaXJlY3Rpb249ZGlyZWN0aW9uLAogICAgICAgICAgICBwcmlvcml0eT1BbGVydFByaW9yaXR5LkhJR0gsCiAgICAgICAgICAgIGN1cnJlbnRfcHJpY2U9Y3VycmVudCwKICAgICAgICAgICAgdHJpZ2dlcl9wcmljZT1jdXJyZW50LAogICAgICAgICAgICBzdG9wX2xvc3M9cm91bmQoc3RvcCwgMiksCiAgICAgICAgICAgIHRhcmdldD1yb3VuZCh0YXJnZXQsIDIpLAogICAgICAgICAgICByaXNrX3Jld2FyZD1hYnModGFyZ2V0IC0gY3VycmVudCkgLyBhYnMoY3VycmVudCAtIHN0b3ApIGlmIGFicyhjdXJyZW50IC0gc3RvcCkgPiAwIGVsc2UgMCwKICAgICAgICAgICAgdHJpZ2dlcl9wcm9iYWJpbGl0eT0wLjYsCiAgICAgICAgICAgIHdpbl9wcm9iYWJpbGl0eT0wLjU1LAogICAgICAgICAgICBtaW51dGVzX3RvX3RyaWdnZXI9MCwKICAgICAgICAgICAgaGVhZGxpbmU9ZiJ7c3ltYm9sfSBEQUlMWSBTUVVFRVpFICh7ZGlyZWN0aW9uLnVwcGVyKCl9KSAtIEJCIFdpZHRoIHtiYl93aWR0aDouMWZ9JSIsCiAgICAgICAgICAgIHJlYXNvbmluZz1bCiAgICAgICAgICAgICAgICAiRGFpbHkgQm9sbGluZ2VyIEJhbmRzIElOU0lERSBLZWx0bmVyIENoYW5uZWxzID0gbXVsdGktZGF5IHZvbGF0aWxpdHkgc3F1ZWV6ZSIsCiAgICAgICAgICAgICAgICBmIkJCIFdpZHRoOiB7YmJfd2lkdGg6LjFmfSUgKHRpZ2h0ID0gZXhwbG9zaXZlIGJyZWFrb3V0IGltbWluZW50KSIsCiAgICAgICAgICAgICAgICBmIk1vbWVudHVtOiB7J2J1bGxpc2gnIGlmIG1vbWVudHVtID4gMCBlbHNlICdiZWFyaXNoJ30gKGNsb3NlIHsnYWJvdmUnIGlmIG1vbWVudHVtID4gMCBlbHNlICdiZWxvdyd9IDIwIFNNQSkiLAogICAgICAgICAgICAgICAgZiJBVFI6ICR7YXRyOi4yZn0gfCBTd2luZyB0cmFkZSAtIGhvbGQgb3Zlcm5pZ2h0IiwKICAgICAgICAgICAgXSwKICAgICAgICAgICAgdGltZV93aW5kb3c9IkRBSUxZIiwKICAgICAgICAgICAgbWFya2V0X3JlZ2ltZT0ibmV1dHJhbCIsCiAgICAgICAgICAgIHRyYWRlX3N0eWxlPSJtdWx0aV9kYXkiLAogICAgICAgICAgICBzZXR1cF9jYXRlZ29yeT0iY29uc29saWRhdGlvbiIsCiAgICAgICAgICAgIHNjYW5fdGllcj0ic3dpbmciLAogICAgICAgICAgICBkaXJlY3Rpb25fYmlhcz1kaXJlY3Rpb24sCiAgICAgICAgICAgIGV4cGlyZXNfYXQ9KGRhdGV0aW1lLm5vdyh0aW1lem9uZS51dGMpICsgdGltZWRlbHRhKGhvdXJzPTI0KSkuaXNvZm9ybWF0KCkKICAgICAgICApCgo="


def main():
    check = "--check" in sys.argv
    src = open(FILE, encoding="utf-8").read()
    cur_sha = hashlib.sha256(src.encode("utf-8")).hexdigest()
    print(f"file            : {FILE}")
    print(f"live SHA        : {cur_sha}")
    print(f"expected SHA    : {PRE_FILE_SHA}")
    if cur_sha != PRE_FILE_SHA:
        print("\nABORT: live file SHA != expected baseline. The DGX file has DRIFTED.")
        print("Re-run extract_func.py _check_daily_squeeze and rebase. NOTHING was written.")
        sys.exit(2)

    old = base64.b64decode(OLD_B64).decode("utf-8")
    new = base64.b64decode(NEW_B64).decode("utf-8")
    n = src.count(old)
    print(f"OLD anchor count: {n}  (MUST be 1)")
    if n != 1:
        print("\nABORT: OLD anchor not uniquely found. NOTHING was written.")
        sys.exit(3)

    patched = src.replace(old, new, 1)
    post_sha = hashlib.sha256(patched.encode("utf-8")).hexdigest()
    if patched.count(new) != 1 or old in patched:
        print("\nABORT: post-replace self-check failed. NOTHING was written.")
        sys.exit(4)
    print(f"POST SHA        : {post_sha}")

    if check:
        print("\n--check OK: guards pass, OLD found exactly once, replacement is clean.")
        print("Run without --check to apply.")
        return

    bak = FILE + ".v358.bak"
    shutil.copy2(FILE, bak)
    with open(FILE, "w", encoding="utf-8") as f:
        f.write(patched)
    verify = hashlib.sha256(open(FILE, encoding="utf-8").read().encode("utf-8")).hexdigest()
    if verify != post_sha:
        print(f"\nABORT: post-write verify mismatch ({verify} != {post_sha}).")
        sys.exit(5)
    print(f"\nAPPLIED. backup -> {bak}")
    print(f"new live SHA    : {verify}")
    print("Next: pytest -> commit -> ./start_backend.sh --force")


if __name__ == "__main__":
    main()
